### ISSUE TITLE
Item was selected falsely by being dragging to the initial position

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#10]
Consider such case: user starts dragging the list, moved a lot from side to side but luckily stops exactly at same position it was picked.
Item will be selected, but that's not what user needs.
How about counting amount of pixels moved by X axis instead of comparing start/stop positions?
![selected](https://user-images.githubusercontent.com/1753208/46292911-c2e19800-c59a-11e8-8e83-92925e78b2ea.gif)

**Comment by asmyshlyaev177** [comment]
> stops exactly at same position it was picked.

It is very rare case.

> Item will be selected, but that's not what user needs.

Yeap, it a bug, will think how to fix it.
I use start and stop for count pixels.

**Comment by NeXTs** [comment]
https://stackoverflow.com/a/8686670/1221082

**Comment by asmyshlyaev177** [comment]
Thanks, will fix it later.

**Comment by asmyshlyaev177** [comment]
I fixed it [86685af66a1db1e6aa33e2a4150308a823f8c769](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/commit/86685af66a1db1e6aa33e2a4150308a823f8c769)
