### ISSUE TITLE
Scrolling ScrollMenu will also scroll parent container's vertical scroll

### ISSUE THREAD

**Issue by iGoodie** [asmyshlyaev177/react-horizontal-scrolling-menu#101]
**Describe the bug**
When the ScrollMenu is under a container with vertical scrolls, mouse wheel scrolls both of them.

**To Reproduce**
1. Create a div with `height:100000px` and `overflow-y:scroll`
2. Put your `ScrollMenu` with a few items under the div
3. Try to scroll `ScrollMenu` with your mouse wheel
4. It will scroll both of them :c

**Comment by socar-bigsur** [comment]
try this!


index.js
```      
<TouchAxis>
          <ScrollMenu
            inertiaScrolling={true}
            inertiaScrollingSlowdown={0.6}
            alignOnResize={false}
            onSelect={clickRecommendedCar} // onClick
            wheel={false}
            alignCenter={false}
            transition={0.4}
            data={Cards(recommendedCarsData?.recommendedCars)}
          />
      </TouchAxis>
```
TouchAxis.tsx
```
import React, { useState } from "react";

interface IInitialTouchState {
    originX: number;
    originY: number;
    axis?: "v" | "h";
}

const initialTouchState: IInitialTouchState = {
    originX: 0,
    originY: 0,
};

const TouchAxis = ({ children }) => {
    const [touchInfo, setTouchInfo] = useState(initialTouchState);

    const handleTouchStart = (event: React.TouchEvent): void => {
        const { clientX, clientY } = event.touches[0];
        setTouchInfo({ originX: clientX, originY: clientY });
        document.body.style.overflow = 'auto';
    }

    const handleTouchEnd = (): void => {
        setTouchInfo(initialTouchState);
        document.body.style.overflow = 'auto';
    };

    const setDominantAxis = (diffX: number, diffY: number) => {
        const isVertical = (Math.abs(diffY) > 20) && (Math.abs(diffX) < Math.abs(diffY));
        const isHorizontal = (Math.abs(diffX) > 20) && (Math.abs(diffX) > Math.abs(diffY));

        if (isHorizontal) {
            setTouchInfo({ ...touchInfo, axis: "h" });
            document.body.style.overflow = 'hidden';
            return;
        }

        if (isVertical) {
            setTouchInfo({ ...touchInfo, axis: "v" });
            return;
        }
    }

    const handleTouchMove = (event: React.TouchEvent): void => {
        const { clientX, clientY } = event.touches[0];
        const { originX, originY, axis } = touchInfo;

        if (!axis) {
            const diffX = clientX - originX;
            const diffY = clientY - originY;
            setDominantAxis(diffX, diffY);
        }
    }

    const handleTouchMoveCapture = (event: React.TouchEvent): void => {
        const { axis } = touchInfo;
        if (axis === 'v') {
            event.stopPropagation()
        }
    }

    return <div
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        onTouchMove={handleTouchMove}
        onTouchMoveCapture={handleTouchMoveCapture}
    >
        {children}
    </div>
};

export default TouchAxis
```

**Comment by asmyshlyaev177** [comment]
Check out example for V2, https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/main/example-nextjs/helpers/useHideBodyScroll/index.ts

**Comment by gavr123456789** [comment]
@asmyshlyaev177 this link is dead

**Comment by asmyshlyaev177** [comment]
> This link is dead Looks like it was this example https://codesandbox.io/s/no-scrollbar-and-buttons-position-c3kn5?file=/src/index.tsx

Link works, checked it just now.

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/159117541-fdaa712a-553c-4edb-bddb-5a8918a6e592.png)
Still 404 for me

**Comment by asmyshlyaev177** [comment]
> ![image](https://user-images.githubusercontent.com/30507409/159117541-fdaa712a-553c-4edb-bddb-5a8918a6e592.png) Still 404 for me

You posted link to github.

**Comment by gavr123456789** [comment]
Yea, because I was talking about the last link you posted in this issue, sorry for misunderstanding. 

> Check out example for V2, https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/main/example-nextjs/helpers/useHideBodyScroll/index.ts

**Comment by asmyshlyaev177** [comment]
> Yea, because I was talking about the last link you posted in this issue, sorry for misunderstanding.
> 
> > Check out example for V2, https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/main/example-nextjs/helpers/useHideBodyScroll/index.ts

Just moved it to other folder https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/main/example-nextjs/helpers/usePreventBodyScroll/index.ts
