### ISSUE TITLE
How to set initial position to end

### ISSUE THREAD

**Issue by pegasus1982** [asmyshlyaev177/react-horizontal-scrolling-menu#104]
I'm making event list with this horizontal slider.
One is newer event list, and another one is older event list.

For the newer event list there is not problem.
But I wanna show older event with reversed order.
For this, I want set initial position of older event list to the end.
How can I implement it?

**Comment by asmyshlyaev177** [comment]
It's not implemented yet.

Can pass `translate` prop with scrolled value(if items are static)

Can pass `selected` item and `scrollToSelected`

Can try pass ref to `ScrollMenu`, get offset to last item `const offset = ref. getOffsetToItemByKey(itemKey)` and set it `ref.setState({ translate: offset })`

**Comment by asmyshlyaev177** [comment]
Can you try V2 and example https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/0ff91827876bf9377dc62f74a5a3451d2d9faa0a/example-nextjs/pages/index.tsx#L109
