### ISSUE TITLE
Menu Stops Scrolling after 6th element, drags back to 5th element on mouse release

### ISSUE THREAD

**Issue by ademidun** [asmyshlyaev177/react-horizontal-scrolling-menu#105]
**Describe the bug**
My horizontal scrolling menu is being displayed dynamically. A user click's "Show Menu" and then the component is loaded. Each menu item is an image of variable width.

After the 6th element is displayed, the 7th element is half visible on screen but when I click the right arrow, nothing happens.

When I try to scroll right, it drags me back to the currently visible element if I release the mouse.

It seems like sometimes it works and doesn't work based on the screen width.

Sandbox Demo: https://codesandbox.io/s/react-horizontal-scrolling-menu-uyte1?file=/src/index.js

Potential duplicate of https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/79 but I don't understand [the solution](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/79#issuecomment-542182336) posted there. Also see #65 , but they also don't explain what the fix is.

**Screenshots**
![Screen Shot 2020-05-02 at 8 03 23 AM](https://user-images.githubusercontent.com/9806858/80863658-da3ba800-8c4b-11ea-9aa2-a0711303ae6c.png)

**Comment by jasonejavier** [comment]
Same issue

**Comment by omaowed** [comment]
Had this issue, solved it by removing margins in `menu-item-wrapper ` class in css or `itemStyle` in JSX

To add space between the children use padding instead

**Comment by ahmed19chebil** [comment]
thank you @ghost for the tip, it worked for me
i ve just overrided the itemStyle by changing margins with paddings
`itemStyle={
              {margin:'0 0 0 0',padding: '19px 11px 84px 19px',marginTop:'10px'}
            }`

> Had this issue, solved it by removing margins in `menu-item-wrapper ` class in css or `itemStyle` in JSX
> 
> To add space between the children use padding instead

**Comment by asmyshlyaev177** [comment]
Looks like fixed, try V2 version, should works better.
