### ISSUE TITLE
Url access and scroll the list

### ISSUE THREAD

**Issue by GodlFox** [asmyshlyaev177/react-horizontal-scrolling-menu#106]
I know we have translate as props but how could we make the menu scroll if we access the link via url.
Regards

**Comment by asmyshlyaev177** [comment]
Not sure what you mean.

**Comment by Mohammedalasaad** [comment]
Hi @asmyshlyaev177 
I mean if we have categories like this image
<img width="1333" alt="Screenshot 2020-05-15 at 12 37 01" src="https://user-images.githubusercontent.com/48674512/82041681-d9256480-96a8-11ea-9e79-1911772e1536.png">
And there are more categories but must scroll to see.. lets say category called "Software"  and if we access the url site.com/category/software so we are on the page and its working but the scroll still hidden, I mean it does not scroll to the active category.

hope thats clear.
Thanks

**Comment by asmyshlyaev177** [comment]
You can pass `selected={'software'}` item and `scrollToSelected={true}` prop.

**Comment by Mohammedalasaad** [comment]
Yes I have that already :) and the category became active but I must scroll to see that category.
```
     <ScrollMenu
                    data={this.menu}
                    arrowLeft={ArrowLeft}
                    arrowRight={ArrowRight}
                    wheel={false}
                    alignCenter={false}
                    hideArrows={true}
                    hideSingleArrow={true}
                    scrollBy={2}
                    selected={this.props.selected}
                    onSelect={this.props.onSelect}
                    scrollToSelected={true}
                    onUpdate={this.trackSubCategoryMenuSwipe}
                />
```

**Comment by asmyshlyaev177** [comment]
I see, tbh don't have much time to support library, having plans to rewrite it, but it still very early stages.

**Comment by asmyshlyaev177** [comment]
Can you try V2 and example https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/0ff91827876bf9377dc62f74a5a3451d2d9faa0a/example-nextjs/pages/index.tsx#L109
