### ISSUE TITLE
Content's onClick is fired after dragging

### ISSUE THREAD

**Issue by delanni** [asmyshlyaev177/react-horizontal-scrolling-menu#108]
**Describe the bug**
I think this could be considered a bug. 
If you drag and release an item in the list, the list item's own onClick handler fires, usually when you drag-and-release, it shouldn't count as clicking, or tapping. The problem, I think is that the consumer can't distinguish between the mouse-release event and the proper click event.

My hunch, is because the container is translating with the element in the same place under it, it looks like the user never moved their mouse, so the mouse-down and mouse-up events fire on the same spot, thus they'll count as a click. I'll dig myself in the code soon, to see if I can come up with a solution, but maybe it's a lot faster for you. 

**To Reproduce**

0. Have a setup where your `data` contains HTML elements with `onClick` handlers, and enable drag scrolling
1. Drag any element
2. Release the element
3. The `onClick` handler will fire.

**Example repo**
https://codesandbox.io/s/react-horizontal-scrolling-menu-ez20r?file=/src/index.js
^ just drag and release.

**Desktop (please complete the following information):**
_doesn't matter_

**Smartphone (please complete the following information):**
_doesn't matter_

**Additional context**

**Comment by lexeech** [comment]
I tried to fix it, but figured out that in your case you have to use only onSelect prop to handle child's fires.

**Comment by delanni** [comment]
onSelect will give you a key of which element was clicked. It's a really different API through which you only get a 'key' - you'd have to have the elements and their handlers tightly coupled with the container to be able to resolve the key to a certain action handler, or use some sort of similar fashion lookup. 

Having proper onClick handlers fire on element clicks is a different approach, this menu is only a container, and each item is an entity of their own, knowing how to react to a click (not a drag).

**Comment by Vitali883** [comment]
Having the same issue. I think this is important problem. Need to think how to fix

**Comment by asmyshlyaev177** [comment]
You can try version 2.
