### ISSUE TITLE
The selected item doesn't come to the center of view

### ISSUE THREAD

**Issue by behosseini** [asmyshlyaev177/react-horizontal-scrolling-menu#109]
Hi,

I wrapped `ScrollMenu` around a `functional component` as shown below:

```
export const Scroll = ({ list, selected, handleSelect }) => {
  return (
    <div>
      <ScrollMenu
        data={Menu(list, selected)}
        selected={selected}
        onSelect={handleSelect}
        scrollToSelected={true}
        inertiaScrolling={true}
      />
    </div>
  );
};
```

1) In my list I have `[100, 250, 350, 450, 550, 1000]`, and the selected value is 1000. As it's seen, 1000 is all the way down the list. When the app runs, 1000 gets selected automatically but it is not seen on the current view until I manually scroll to it although I have `scrollToSelected={true}`.

What could possibly be causing the issue?

2) Also, when I manually select an item, it does not automatically come to the center of the view. How can I solve this?
![Capture](https://user-images.githubusercontent.com/35468490/84589917-10af3a00-ae2a-11ea-9b94-8db3457952db.PNG)

Should I somehow use `componentRef.scrollTo(selected)`? If so, how do I need to implement `componentRef`?

Thank you in advance.

**Comment by asmyshlyaev177** [comment]
Can try to use `componentRef`, sorry don't have much time to support this library.

**Comment by behosseini** [comment]
Thanks a lot for dedicating your time making this library.

After hours of digging I think I finally found the issue.

In the `ScrollMenu` component the value for `selected` must be a string only (and not an integer), otherwise `scrollToSelected={true}` doesn't work. I could get around it by adding a `.toString()` method.
