### ISSUE TITLE
Positioning arrow absolutely - remove the space leftover for arrows

### ISSUE THREAD

**Issue by ashvin777** [asmyshlyaev177/react-horizontal-scrolling-menu#110]
**Describe the bug**
Not able to remove the front space adding up for arrow which is not required.

**To Reproduce**
Set scroll menu style to as such 
```
 .scroll-menu-arrow {
            position: absolute;
            height: 100%;
            z-index: 100;
            display: flex;
            align-items: center;
            padding: 5px;
            transition: background 500ms;
            cursor: pointer;
            visibility: hidden;
```

**Screenshots**
<img width="355" alt="Screenshot 2020-07-03 at 8 08 44 PM" src="https://user-images.githubusercontent.com/8143154/86479075-17fe9f00-bd69-11ea-8b73-9512313f1a11.png">

**Comment by kruserr** [comment]
Have you tried to disable alignCenter?

```
<ScrollMenu
  ...
  alignCenter={false}
  ...
 />
```

**Comment by asmyshlyaev177** [comment]
I see it's fixed, can check out V2, there can use CSS for position arrows as you like.
