### ISSUE TITLE
Limit number of showing items to 1

### ISSUE THREAD

**Issue by reharik** [asmyshlyaev177/react-horizontal-scrolling-menu#111]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Would it be possible to limit the number of items shown to 1.  In other words when you scroll left a new image slides in but only 1 image.  Essentially making this a carousel.  I am (going to be) using it as a thumbnail viewer.  When you click on an image(item) it will launch a carousel. This seems to have all the features I'll need in a carousel and it would be nice to be able to use the same component with different settings.
It's actually my day off and I shouldn't even be doing this :) but on monday, I'll implement this proper.  At which point I'll dig in and see a) if this is already possible and b) if not, what it would take to make it happen.  
Please let me know if this is already possible,  b) if you think this would be a good feature and c) if you have any ideas of where I should look, or what files would be a good starting place.
Thanks

**Comment by asmyshlyaev177** [comment]
a) Not possible via this library.
b) Not sure about it, for display 1 item probably better use some gallery library.
c)  Possible if you have fixed container width and can adjust margin around items. But i think some library for gallery can be better alternative.

**Comment by asmyshlyaev177** [comment]
You can try version 2.
