### ISSUE TITLE
Arrow animation(hiding/showing) massive delay

### ISSUE THREAD

**Issue by reifnotreef** [asmyshlyaev177/react-horizontal-scrolling-menu#115]
**Description**  
On some computers, some of the time, the arrows have a massive delay(2-3 seconds) before showing/hiding.
This is happening on someone else's computer and I cannot reproduce it locally. This is *only* happening in Safari 13.1 on a Macbook pro running osx 10.15.

I have tested this behaviour via BrowserStack on Safari 11.1, 12.1, and 13.1 but cannot get it to happen. I have also tested on a separate machine running the same version of osx/safari and cannot reproduce it.

**To Reproduce**
So far unable to reproduce besides 1 person's computer specifically.

**Example repo**
Private repo, unable to share entire repo

**Desktop**
 - OS: OSX 10.15
 - Browser: Safari 13.1

**Additional context**
I am mostly opening this issue to see if anyone else has faced this specific issue, whether on a different platform or not.
If this is a bug, known or otherwise, I want to see if we can figure out a way to fix it! :)

**Component call =>**
```
      <ScrollMenu
        alignCenter={false}
        arrowDisabledClass={classes.disabledArrow}
        arrowLeft={
          <div className={classes.arrowLeft}>
            <Icon icon="chevronLeft" />
          </div>
        }
        arrowRight={
          <div className={classes.arrowRight}>
            <Icon icon="chevronRight" />
          </div>
        }
        hideArrows
        hideSingleArrow
        data={scrollableCards}
        dragging
        wheel={false}
        transition={0.5}
        translate={0.3}
        scrollBy={1}
      />
```
**Data =>**
```
  const scrollableCards = IndustrialInfo.map((card, index) => {
    return (
      <div
        className={cn(classes.cardWrapper, 'menu-item', {
          [classes.firstWrapper]: index === 0,
          [classes.lastWrapper]: index === IndustrialInfo.length - 1,
        })}
        // eslint-disable-next-line react/no-array-index-key
        key={index + 1}
      >
        <div className={classes.headerWrapper}>
          <Icon icon={card.icon as DottidIconTypes} className={classes.headerIcon} />
          <h3 className={classes.headerCopy}>{card.header}</h3>
        </div>
        <div className={classes.listWrapper}>
          {card.rows.map((row) => {
            return (
              <div className={classes.listRow}>
                <p>{row.name}</p> <p>{row.value || '-'}</p>
              </div>
            );
          })}
        </div>
        <div className={classes.notesWrapper}>
          <p className={classes.notesHeader}>Notes</p>
          <p className={classes.notesCopy}>{card.notes || 'N/A'}</p>
        </div>
      </div>
    );
  });
```
**Styling for arrows =>**
```
    arrowLeft: {
      extend: 'arrowStyles',
      left: 20,
    },
    arrowRight: {
      extend: 'arrowStyles',
      right: 20,
    },
    arrowStyles: {
      background: colors.white,
      boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.16)',
      borderRadius: 100,
      height: '48px !important',
      width: '48px !important',
      display: 'grid',
      placeItems: 'center',
      position: 'absolute',
      top: 151,
      zIndex: 2,
    },
    disabledArrow: {
      visibility: 'hidden',
    },
```

**Comment by asmyshlyaev177** [comment]
Can you check is this bug exists with V2?

Can't do anything about it until can reproduce it.

**Comment by reifnotreef** [comment]
Hey @asmyshlyaev177 I totally forgot I had no come back and closed this issue. Since no one else has commented on it I am willing to chock this up to a local machine issue. I was unable to reproduce this in any way.

Since then we have changed our design slightly and haven't run in to this issue since then.
