### ISSUE TITLE
How to have the same initialOffset when scroll back to firstItemVisible ?

### ISSUE THREAD

**Issue by Suissehide** [asmyshlyaev177/react-horizontal-scrolling-menu#119]
I start with an initial offset of 200px. When I scroll one way and then come back, there is no more offset.
Is there a way to keep a fixed distance at the start of the ScrollMenu?

**Comment by antoninu** [comment]
I have the same problem, I have tried everything with the component's ref but nothing works for me

**Comment by asmyshlyaev177** [comment]
No way to keep offset after scroll.

Can use CSS padding for create an offset and keep it.

Checkout example for V2(in commented code with //NOTE) https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-d8m29?file=/src/index.tsx
