### ISSUE TITLE
Incorrect disabled arrow on resize

### ISSUE THREAD

**Issue by petr-hajek** [asmyshlyaev177/react-horizontal-scrolling-menu#120]
**Describe the bug**
When there is difference in visibility of on resize there is case when the arrow is hidden. User then cannot reach the rest of the menu.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-horizontal-scrolling-menu-forked-hir63?file=/src/index.js with a view as a small screen
2. Scroll to the end (just 5 items) and select the last item
3. Resize to large width
4. The left arrow is hidden

**Example repo**
https://codesandbox.io/s/react-horizontal-scrolling-menu-forked-hir63?file=/src/index.js 

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/38785076/96012100-12beef00-0e44-11eb-9105-c74b33265a94.png)

**Desktop (please complete the following information):**
FF/Win10

**Additional context**
I think the visibility is based just on comparing the width of menu and menuitems. So it needs to either 
a) transform on resize in such a way that all items will become visible if possible
b) change the way visibility is calculated

**Comment by asmyshlyaev177** [comment]
Can you try version 2?
