### ISSUE TITLE
I want to use onFirstItemVisible property component render infinite times.

### ISSUE THREAD

**Issue by rohail411** [asmyshlyaev177/react-horizontal-scrolling-menu#121]
I want to perform some action when the first item visible. I can use onFirstItemVisible property when I pass the method on it component updates infinite times.

**Comment by VikrantShirvankar** [comment]
I think you are using `this.setState()` method inside `onFirstItemVisible` callback. This could be the reason of infinite re-rendering.

**Comment by asmyshlyaev177** [comment]
Can you try version 2?
