### ISSUE TITLE
[Request]: Can you enable discussions in this project?

### ISSUE THREAD

**Issue by rotimi-best** [asmyshlyaev177/react-horizontal-scrolling-menu#124]
I am sure everyone has heard of the new [github discussion](https://docs.github.com/en/discussions) available to projects (currently in beta). Can you enable it for this project? People can have conversations that are not necessarily issues (just like this).

**Comment by asmyshlyaev177** [comment]
Enabled.

**Comment by rotimi-best** [comment]
Thank you :)
