### ISSUE TITLE
Flickering occurs caused by the 990000px fixed width

### ISSUE THREAD

**Issue by korbav** [asmyshlyaev177/react-horizontal-scrolling-menu#126]
**Describe the bug**

Due to the hard coded 990000px width which is set by the component to the class `.menu-wrapper--inner`, browser doesn't behave smoothly and flickering is observed in Chrome.

**To Reproduce**

I just instantiated the component and displayed it in the mobile simulation layout featured of Chrome.

**Screenshots**

Native result (Flickering) :
![2021-01-31_07h39_53](https://user-images.githubusercontent.com/6184386/106377963-9f140400-6398-11eb-84e0-3ea6a3b31f4c.gif)

Result with overriding the width to 5000px (No flickering) :
![2021-01-31_07h40_59](https://user-images.githubusercontent.com/6184386/106377969-b521c480-6398-11eb-94e3-a85135a75a75.gif)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 88.0.4324.104

**Additional context**

As shown above, as soon as I enforce the width of `.menu-wrapper--inner` to something lower, for example, 5000px, flickering disappears immediately.

**Comment by mozartatplay** [comment]
I also noticed this on a react web application I built a year ago which has always worked fine on hrome - a few weeks ago when chrome updated to version 88, the flickering occured. But its still gives no problems in Safari. Why would this suddently happen now?

Chrome:

https://user-images.githubusercontent.com/26509490/106949581-d20e1d00-6735-11eb-8ce8-126fee8c4788.mp4

Safari:

https://user-images.githubusercontent.com/26509490/106949693-f669f980-6735-11eb-9468-494f70afac51.mp4

**Comment by asmyshlyaev177** [comment]
Can't control browsers internals, can guess that is related to GPU and `translate3d`.

About width, you can open PR, it's not so complex changes.

**Comment by korbav** [comment]
> 
> 
> Can't control browsers internals, can guess that is related to GPU and `translate3d`.
> 
> About width, you can open PR, it's not so complex changes.

Using hardcoded arbitrary values is unfortunately usually not a desirable thing.
I may miss something but why would we even need to have this width fixed?
I guess the width is being fixed for now only to ensure that we have enough horizontal space to display the menu in one single line. 

I would recommend another approach, letting the browser deal with that for us.

Replacing `width:"990000px"` by `whiteSpace:"nowrap"` solves the problem for me.

@mozartatplay Please check if it works for you, if so, I will create a PR.

**Comment by asmyshlyaev177** [comment]
@korbav Seems to work with `white-space`, can open PR.

**Comment by korbav** [comment]
> 
> 
> @korbav Seems to work with `white-space`, can open PR.

PR created here https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/126

**Comment by mozartatplay** [comment]
Super - the whiteSpace:"nowrap" change works perfectly for me on Chrome - no more flickering! Thanks for the quick work @korbav

**Comment by asmyshlyaev177** [comment]
Published new version with this PR.

**Comment by arminydy** [comment]
@korbav @asmyshlyaev177 Thanks! it works like a charm.
