### ISSUE TITLE
Dragging falsely starts by clicking right mouse button

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#13]
Black circle - left mouse click
Green circle - right mouse click

![rightclick](https://user-images.githubusercontent.com/1753208/46532883-5670dc80-c8ab-11e8-924a-37332d4ecbb8.gif)

**Comment by asmyshlyaev177** [comment]
Fixed it, check new version.

**Comment by NeXTs** [comment]
Great! Thanks
