### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by bipinstha7** [asmyshlyaev177/react-horizontal-scrolling-menu#133]
Is the infinite scroll possible? I can't see this feature in the doc. Can I do it with some tweaks?

## My Requirement:
Fetch data for every right arrow click and if there is no more data to be fetched, Do infinite scrolling.

**Comment by asmyshlyaev177** [comment]
Hi, not sure if it's possible, can try with `onLastItemVisible` callback.

**Comment by bipinstha7** [comment]
@asmyshlyaev177 , working with that callback. Let's hope for the best. If you come up with any solution please let me know. Thank you :)

**Comment by bipinstha7** [comment]
Hi, I did it with this code when scroll reaches to last data
` const two = this.state[key].slice(0, 2);
        const rest = this.state[key].slice(2, this.state[key].length);
        this.setState({
          data: [...rest, ...two],
        });`

It's working fine but the problem is when the data is rescheduled scroller animation stops working and scrolls step wise or block wise. Any solution please?

**Comment by asmyshlyaev177** [comment]
Easier to find library that support fetch and infinite scroll, should be many galleries/slideshow libraries.

**Comment by asmyshlyaev177** [comment]
Can you try version 2?
