### ISSUE TITLE
Support Mouse Wheel Scroll on track pad Left & right

### ISSUE THREAD

**Issue by ablueplatypus** [asmyshlyaev177/react-horizontal-scrolling-menu#134]
**Describe the bug**

Scroll wheel only works up and down. If you are using a mouse pad and scroll to the left or right the list will not scroll back to the left.  Note gifs below.

**To Reproduce**

1. https://codesandbox.io/s/lpjol1opmq?file=/src/index.js
2. Use the trackpad to scroll right, note the 
3. Scroll to the left notice the list moves back in the wrong direction. 

**Example repo**

Reproduction of bug in codepen
Yes you can see this in the codepen repo you have set up. 
https://share.getcloudapp.com/X6ueWr8p

**Screenshots**

https://share.getcloudapp.com/X6ueWr8p

**Desktop (please complete the following information):**

 - OS: Mac Catalina 10.15.7
 - Browser Chrome
 - Version 89.0.4389.90 

**Smartphone (please complete the following information):**

Did not test this on a phone 

**Additional context**

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0`, it should works.
