### ISSUE TITLE
Issue with scrolling on initial load and resizing

### ISSUE THREAD

**Issue by harikautilya** [asmyshlyaev177/react-horizontal-scrolling-menu#135]
**Describe the bug**
1.unable to scroll on the first load of the dynamic images for a div containing dynamic images
2. The last item is not equal to the items loaded

**To Reproduce**
1. Open the sandbox and copy the website and open a new tab in chrome
2. Click on the right arrow. (Scroll doesnt work)
3. Resize the window by opening inspect or directly resizing 
4. Click on right arrow (Scroll work but doesnt take to last item but can see the item added to the div . Check screeshot)

Codesandbox:
https://codesandbox.io/s/react-horizontal-scroll-isssue-z1u3x?file=/src/App.js

**Desktop (please complete the following information):**
OS : MacOS high sierra
Brower: Chrome 
versions Version 89.0.4389.90 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
None

**Additional context**
![Screen Shot 2021-03-31 at 4 05 36 PM](https://user-images.githubusercontent.com/17510412/113132056-94aca400-923b-11eb-8200-10aa6082e2ec.png)

**Comment by asmyshlyaev177** [comment]
Can you try version 2?
