### ISSUE TITLE
How do I disable vertical scrolling when swiping on a touch device?

### ISSUE THREAD

**Issue by johnvonneumann7** [asmyshlyaev177/react-horizontal-scrolling-menu#136]
How do I disable vertical scrolling when swiping on a touch device?

As far as I could find, I couldn't find such a function.

Here are my options.

```
state = {
  alignCenter: false;
  alignOnResize: false;
  dragging: true;
  wheel: false;
  hideSingleArrow: true;
  inertiaScrolling: true;
}
```

**Comment by asmyshlyaev177** [comment]
Can apply css `overflow-y: hidden;`

**Comment by johnvonneumann7** [comment]
Where should they be added? I've added them to `horizontal-menu``.menu-wrapper``.menu-wrapper--inner`, but none of them work.

**Comment by asmyshlyaev177** [comment]
> Where should they be added? I've added them to `` horizontal-menu``.menu-wrapper``.menu-wrapper--inner ``, but none of them work.

Shouldn't be vertical scrolling, can you reproduce it on codesandbox?

**Comment by johnvonneumann7** [comment]
https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/
We have the same problem on this demo page.
See the video below.

https://user-images.githubusercontent.com/78252058/120744556-38654980-c536-11eb-930e-313b1f23c604.mp4

**Comment by asmyshlyaev177** [comment]
Can try new version https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/137
Now in development.

**Comment by johnvonneumann7** [comment]
tyvm.
How do I add it to an existing project?

**Comment by asmyshlyaev177** [comment]
> tyvm.
> How do I add it to an existing project?

Can install beta version `npm install — save react-horizontal-scrolling-menu@2.0.0-beta.1`

**Comment by johnvonneumann7** [comment]
> Can install beta version `npm install — save react-horizontal-scrolling-menu@2.0.0-beta.1`
I was able to add it successfully.
By the way, it seems that TypeScript is not supported.
How can I use it if my own project consists of Typescript?

Also, there are examples and next.js-example in the repositories, but are there any other
Is there any other documentation for v2?

**Comment by asmyshlyaev177** [comment]
> > Can install beta version `npm install — save react-horizontal-scrolling-menu@2.0.0-beta.1`
> 
> I was able to add it successfully.
> By the way, it seems that TypeScript is not supported.
> How can I use it if my own project consists of Typescript?
> 
> Also, there are examples and next.js-example in the repositories, but are there any other
> Is there any other documentation for v2?

It's in beta, so unfinished, will add docs and possibly ts definitions later.

**Comment by johnvonneumann7** [comment]
Thank you. In the meantime, I'd like to prevent vertical scrolling from occurring in the current version. The environment is probably the same as the demo.
The demo also has vertical scrolling while swiping as well.

**Comment by asmyshlyaev177** [comment]
> Thank you. In the meantime, I'd like to prevent vertical scrolling from occurring in the current version. The environment is probably the same as the demo.
> The demo also has vertical scrolling while swiping as well.

For current version can create styles like `.no-scroll { overflowY: clip; }` for `body`, when menu is focused add this class to body, on blur remove it, similar to this https://stackoverflow.com/questions/37183797/add-class-on-focus-change-using-redux-and-react

**Comment by johnvonneumann7** [comment]
Thank you. I was able to do it safely.
