### ISSUE TITLE
Horizontal scroll bar bug

### ISSUE THREAD

**Issue by neosheps** [asmyshlyaev177/react-horizontal-scrolling-menu#141]
Hi there! Let me explain in our native language :)

У меня есть около 15 предметов внутри меню. Я так-же хочу выводить горизонтальный скролл-бар, но он ведет себя очень странно. Если не использовать прокрутку драгом или колесом мыши, все работает отлично. Но, если сначала прокрутить драгом \ мышью, а потом попробовать скроллбар, он то искривляется, то дергается, то показывает в своих рамках только последние несколько экземпляров меню. 

Я предполагаю, что это связано со свойством `transform`. Есть ли возможность починить или обойти эту ошибку? Библиотека идеально подходит, но мне очень нужен скроллбар. Заранее спасибо за ответ. Скриншоты поведения прилагаю ниже:

![Screenshot from 2021-07-06 14-46-45](https://user-images.githubusercontent.com/37346734/124595378-9fde2400-de69-11eb-9340-5e28dfd8e6db.png)
![Screenshot from 2021-07-06 14-46-59](https://user-images.githubusercontent.com/37346734/124595384-a10f5100-de69-11eb-9b4f-3ad057f9b15d.png)
![Screenshot from 2021-07-06 14-47-16](https://user-images.githubusercontent.com/37346734/124595391-a2407e00-de69-11eb-9711-6f1828378b26.png)

**Comment by asmyshlyaev177** [comment]
С transform много сложностей, пилю новую версию https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/137
Хотя драга там нет, можно попробовать приделать.

**Comment by neosheps** [comment]
@asmyshlyaev177 без драга тяжко будет, у нас юзверы привыкшие всё свайпать. хорошо, понял, спасибо за ответ, я приделаю тогда не нативным браузерным методом

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 без драга тяжко будет, у нас юзверы привыкшие всё свайпать. хорошо, понял, спасибо за ответ, я приделаю тогда не нативным браузерным методом

Драг мышкой или на тачскрине?

**Comment by neosheps** [comment]
@asmyshlyaev177 мышкой. Пользователи привыкли свайпать на экране, заметил закономерность что сейчас чаще стараются драгать элементы со скроллом, нежели чем кликать на стрелочки \ дёргать скроллбар

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 мышкой. Пользователи привыкли свайпать на экране, заметил закономерность что сейчас чаще стараются драгать элементы со скроллом, нежели чем кликать на стрелочки \ дёргать скроллбар

Опубликовал react-horizontal-scrolling-menu@2.0.0-beta.7 с примером как это использовать.
