### ISSUE TITLE
Hide scrollbar and change arrow position

### ISSUE THREAD

**Issue by haksatryabhaswara** [asmyshlyaev177/react-horizontal-scrolling-menu#144]
Dude, i love your work! really really great! but i need backup, i need to hide the scrollbar and change arrow position, can you help to explain how to hide the scroll bar and change arrow position? thanks so much :)

**Comment by asmyshlyaev177** [comment]
Can hide scrollbar via css - https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/62a8d3a1a5b04fd23aa8d50f4ac0fc66dbd03664/example-nextjs/pages/_app.js#L4

What do you mean by change arrow position? Move it where?

**Comment by haksatryabhaswara** [comment]
Hey @asmyshlyaev177 thanks for your reply..
got it, i'll try to hide my scrollbar with your provided link,

I'm sorry if i didn't provide detail information, default arrow position is right and left, can i move them to (lets say) bottom right, so the arrow position on the bottom right..

**Comment by haksatryabhaswara** [comment]
![New Project(42)](https://user-images.githubusercontent.com/68752883/127734117-cbc27092-3969-4109-b6b8-211e2200c46f.png)
I mean moving the arrow like this, at the top, the default, and bottom image, is what i mean..

**Comment by haksatryabhaswara** [comment]
> 
> 
> Can hide scrollbar via css -
> 
> https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/62a8d3a1a5b04fd23aa8d50f4ac0fc66dbd03664/example-nextjs/pages/_app.js#L4
> 
> What do you mean by change arrow position?

**Comment by asmyshlyaev177** [comment]
Can use CSS for that as well, updated codesandbox https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-d8m29?file=/src/index.tsx

**Comment by haksatryabhaswara** [comment]
You're the best! @asmyshlyaev177
