### ISSUE TITLE
Importing causing Error: Element type is invalid

### ISSUE THREAD

**Issue by atlongstaff** [asmyshlyaev177/react-horizontal-scrolling-menu#145]
This morning at about 9 am, a random issue popped up after I reinstalled react-horizontal-scrolling-menu

The full error message is as follows:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

After some research everyone is saying to add {} when importing components. This is not very useful because I have been using them for the entirety of my current project:

`import {ScrollMenu} from 'react-horizontal-scrolling-menu';`

anyways this is probably a really stupid question as I am a react beginner, but I would love some help

**Comment by asmyshlyaev177** [comment]
`import {ScrollMenu} from 'react-horizontal-scrolling-menu';`
This import is for V2 version of library, which version do you use? Look in `package.json`.
Possible that you used V1 before, reinstall to V2 and they are completely different.

**Comment by atlongstaff** [comment]
hey bud thanks for responding, yeah package.json shows 2.0.1:

`    "react-horizontal-scrolling-menu": "^2.0.1",`

**Comment by asmyshlyaev177** [comment]
> hey bud thanks for responding, yeah package.json shows 2.0.1:
> 
> ` "react-horizontal-scrolling-menu": "^2.0.1",`

Misunderstood you a little, can you come back to previous commit and see if it's works? Can find last working commit with `git bisect`

**Comment by atlongstaff** [comment]
hey so we got the code to work when we passed in the left and right arrow props. Are these props required in version 2? Its kind of unclear. Thanks for the help! and you can close this issue whenever!

**Comment by asmyshlyaev177** [comment]
It's supposed to be optional, but, will fix.

**Comment by asmyshlyaev177** [comment]
Published `2.0.2`, should works fine now.
