### ISSUE TITLE
[BUG] visibility of item changes when container is scrolled vertically

### ISSUE THREAD

**Issue by junqdu** [asmyshlyaev177/react-horizontal-scrolling-menu#147]
**Describe the bug**
https://share.getcloudapp.com/2NulKnRl
As you can see in the recording, the visibility of an item changed when the container is scrolled out of view.
I have my arrows hidden when first/last item is not visible, and this cause the arrow to flicker as I scroll.

**To Reproduce**
https://share.getcloudapp.com/2NulKnRl

**Expected behavior**
The visibility of the item should only be relative to its container.

**Screenshots**
https://share.getcloudapp.com/2NulKnRl

**Desktop (please complete the following information):**
 - Browser Chrome 92
 - OS: MacOS 11.5.1

**Additional context**

**Comment by asmyshlyaev177** [comment]
Hi, library use IntersectionObserver API, when element not on screen it's not visible.

For workaround i used use useState and useEffect, can check out example for arrows https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/69e296b113737b41e2fd5b009c6b45aa676fcb80/example-nextjs/pages/index.tsx#L162

I will think maybe can solve this more elegant way.

**Comment by junqdu** [comment]
@asmyshlyaev177 thanks for the reply, I thought the intersection observer can be set on an element instead of the window. Maybe we can set the IntersectionObserver on the container to monitor the element within the container only.

**Comment by asmyshlyaev177** [comment]
IntersectionObserver now use ScrollContainer as `root`, need to take a look, maybe there is a bug.

**Comment by asmyshlyaev177** [comment]
Fixed, published `2.0.3`. Check it out.
Will try to add tests for it later.

**Comment by asmyshlyaev177** [comment]
Thank you for noticing it.

**Comment by junqdu** [comment]
@asmyshlyaev177 thanks for fixing it quickly
