### ISSUE TITLE
"mounted" remains false after init

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#15]
On my project after initialization variable `mounted` remains `false` until we trigger some rerendering.
Because of this clicking to Arrows leads to instant (`0s`) transition to destination point.
Unfortunately I can not reproduce this behavior on demo page (even by adding react-router).
I don't know why mounter remains `false`.. but do we need this `|| !mounted` condition here?
```
export const innerStyle = ({ translate, dragging, mounted, transition }) => {
  return {
    ...
    transition: `transform ${dragging || !mounted ? '0' : transition}s`
  };
};
```

Or, another question:
There is `setMounted` function with variable `initialized` which is used only in this function. What's the reason of this variable? Also, `setMounted` is calling in `componentDidUpdate` only, shouldn't we call it in `componentDidMount` too?

My settings
```
<ScrollMenu
  data={data}
  arrowLeft={<Arrow type="prev" />}
  arrowRight={<Arrow type="next" />}
  onSelect={this.onSelect}
  wheel={false}
  alignCenter={false}
  wrapperClass={style.sliderInner}
  itemClass={style.sliderItem}
/>
```

**Comment by asmyshlyaev177** [comment]
I use _initialized_ for set mounted after first render.

`|| !mounted`  so this for menu don't move on first render.

Try to update to latest version.
Maybe need rewrite this part with mounted, too complicated already.

**Comment by NeXTs** [comment]
I've used latest version, for sure.
I'll try to reproduce this somehow

**Comment by asmyshlyaev177** [comment]
Can you test branch https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/tree/mounted ?
Can install it via npm `npm install asmyshlyaev177/react-horizontal-scrolling-menu#mounted`

**Comment by asmyshlyaev177** [comment]
Ok, i published new version.

**Comment by NeXTs** [comment]
Works now. Thanks!

**Comment by zverexe** [comment]
I'm having the same issue right now. When menu initially loading I have mounter: false, when I click on some menu item, it changes to true;
