### ISSUE TITLE
There should be a Boolean for enable and disable multiselect.

### ISSUE THREAD

**Issue by Shweta689** [asmyshlyaev177/react-horizontal-scrolling-menu#151]
I want to show only 1 item selected at a time. I am not able to do.

Anyone with the same requirements?

**Comment by asmyshlyaev177** [comment]
Hi, you can use string for useState hook, like `const [selected, setSelected] = useState('item1')`

**Comment by asmyshlyaev177** [comment]
Check out example https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-basic-with-select-item-qtxwt?file=/src/index.tsx
