### ISSUE TITLE
Scroll jumps in Safari

### ISSUE THREAD

**Issue by benmneb** [asmyshlyaev177/react-horizontal-scrolling-menu#154]
**Describe the bug**
In safari, when clicking the scroll arrow, the scroll menu just jumps straight to the final scroll position, there is no pleasant scroll animation!

**To Reproduce**
1. Open [the simple demo from the docs](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-basic-example-swg0y?file=/src/index.tsx) in Safari browser
2. Click on the right scroll arrow
3. Watch it jump!

**Expected behavior**
Pleasant, smooth scroll animation like in Firefox/Chrome.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Safari 14.1.1 (16611.2.7.1.4)
 - MacOS 11.4 (Big Sur)

**Additional context**
Thanks for the great project!

**Comment by asmyshlyaev177** [comment]
Safari doesn't support[ `smooth` option for `ScrollIntoView`](https://caniuse.com/scrollintoview).
Try to use [smoothScroll polyfill](https://github.com/iamdustan/smoothscroll) and let me know if it's works.

**Comment by benmneb** [comment]
[It does scroll smoothly](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-smooth-scroll-polyfill-0znt5)... but it also introduces new bugs: 1) when the window has a Y overflow, clicking either button (left or right) will scroll the window down, 2) clicking scroll left button will only scroll by one item, not the usual full vw of items.

**Comment by asmyshlyaev177** [comment]
> [It does scroll smoothly](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-smooth-scroll-polyfill-0znt5)... but it also introduces new bugs: 1) when the window has a Y overflow, clicking either button (left or right) will also scroll the window down, 2) clicking scroll left button will only scroll by one item, not the usual full vw of items.

Damn, can you try [this one](https://github.com/magic-akari/seamless-scroll-polyfill)? Just i'm on linux and hard to test it on safari.

**Comment by benmneb** [comment]
That one seems to [work good](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-webkit-scroll-polyfill-0znt5?file=/src/index.tsx)!

Its [twice the size of the other one](https://bundlephobia.com/package/seamless-scroll-polyfill@1.2.4), but tree-shakeable, and if I'm not mistaken, from your code [here](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/9ba5b5df726d223087814613a9c657b6578a614a/src/helpers.ts#L41), the only import needed to make it work is `elementScrollIntoViewPolyfill`... which would save us a whopping **_4kb_** 😎

**Comment by asmyshlyaev177** [comment]
> That one seems to [work good](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-webkit-scroll-polyfill-0znt5?file=/src/index.tsx)!
> 
> Its [twice the size of the other one](https://bundlephobia.com/package/seamless-scroll-polyfill@1.2.4), but tree-shakeable, and if I'm not mistaken, from your code [here](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/9ba5b5df726d223087814613a9c657b6578a614a/src/helpers.ts#L41), the only import needed to make it work is `elementScrollIntoViewPolyfill`... which would save us a whopping **_0.4kb_**

Cool! Will update example and README, maybe [Safari will support it,](https://bugs.webkit.org/show_bug.cgi?id=161611) i hope.

**Comment by benmneb** [comment]
🤞
