### ISSUE TITLE
Touch options without native scroll?

### ISSUE THREAD

**Issue by ramirezcgn** [asmyshlyaev177/react-horizontal-scrolling-menu#155]
I know you put as a plan to use native browser scroll functionality, but for my use case I need the touch/swipe options without the scroll bar, can I send a PR to allow this?

Regards

**Comment by asmyshlyaev177** [comment]
Sure, touch should works, can hide scrollbar via css line 16 (hideScrollbar.css) here https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-d8m29?file=/src/index.tsx
