### ISSUE TITLE
[BUG] Documentation is incorrect for scrollToItem parameters

### ISSUE THREAD

**Issue by jasondecamp** [asmyshlyaev177/react-horizontal-scrolling-menu#157]
The documentation for V2 VisibilityContext API states:
```
scrollToItem | (item, behavior, inline, block) => void
```
When it is invoked as such:
```
const { getItemById, scrollToItem } = useContext(VisibilityContext)
const handleClick = (myItemId) => {
  const myItem = getItemById(myItemId);
  scrollToItem(myItem);
}
```
The browser throws:
```
index.umd.js:1 Uncaught TypeError: e.scrollIntoView is not a function
    at index.umd.js:1
```

Based on the code and doing my own debugging I believe the API is actually expecting the DOM element of my item not the item itself. I have tested instead using:
```
scrollToItem(item.entry.target);
```
^ this code snippet does work to scroll to the intended item, but is making assumptions about the shape of the item data that is not documented and may be unstable in minor version releases.

I'm not sure if this is something that can/should be updated in the API functionality to match the documentation (which would be an easier developer interface) or if the documentation should be updated to match the implementation. Either way something should be updated and anyone else who struggles to understand how to use this function can see this issue to see a work-around.

**Comment by asmyshlyaev177** [comment]
> scrollToItem(item.entry.target);

It's correct, it's expecting DOM node, need to update documentation.

**Comment by asmyshlyaev177** [comment]
Changed `scrollIntoView` to accept `IOItem` too, version `2.0.10`
