### ISSUE TITLE
On electron the Left right Buttons doesn't work

### ISSUE THREAD

**Issue by muyiwa-felixson** [asmyshlyaev177/react-horizontal-scrolling-menu#17]
Running the same app without electron, the buttons work. But once it's on electron they become unresponsive.

**Comment by asmyshlyaev177** [comment]
I see, will try to figure out why.

**Comment by asmyshlyaev177** [comment]
Can you select scrolling menu in react devtools and show variables
```
$r.allItemsWidth
$r.menuWidth
```

**Comment by asmyshlyaev177** [comment]
Must work now https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/pull/19
