### ISSUE TITLE
[BUG] Please help to resolve this type declaration

### ISSUE THREAD

**Issue by aromal-sasidharan** [asmyshlyaev177/react-horizontal-scrolling-menu#170]
![image](https://user-images.githubusercontent.com/5155674/140032653-5fa5f25b-65e5-4a93-b857-0625f8b5aff2.png)

**Comment by asmyshlyaev177** [comment]
Hi, how to reproduce it?

**Comment by asmyshlyaev177** [comment]
Suspecting that it's `labeled tuple` from TS 4 https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#labeled-tuple-elements
Can you update TS version?

**Comment by asmyshlyaev177** [comment]
Published fixed version, should work with TS < 4.
