### ISSUE TITLE
[BUG]: isLastItemVisible still returns false when menu items have reduced to be visible

### ISSUE THREAD

**Issue by hennadiy-kudashev** [asmyshlyaev177/react-horizontal-scrolling-menu#171]
**Describe the bug**
When menu items have reduced so that all items are visible, however isLastItemVisible returns false.

**To Reproduce**
1. Go to https://codesandbox.io/s/upbeat-fire-qd9pe?file=/src/arrows.tsx:1234-1251
2. Click on 'Remove the last item' until all items are visible.
3. Right Arrow is still visible.

**Expected behavior**
Right Arrow should be hidden when all items are visible

**Screenshots**
<img width="530" alt="Screenshot 2021-11-09 at 11 47 23" src="https://user-images.githubusercontent.com/13120633/140901683-7da97ebc-8683-4a13-9cad-fa525389db0a.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome 95]
 - OS: [e.g. macOS 10.15]

P.S. Thanks for the great component.

**Comment by asmyshlyaev177** [comment]
Hi, tnx for reporting a bug!
I see it, have idea how to fix, but need some time for test it.

**Comment by asmyshlyaev177** [comment]
Fixed in version '2.5.2', check it out.

**Comment by hennadiy-kudashev** [comment]
Thanks, tested - works perfect ✅
