### ISSUE TITLE
[BUG] parent container scroll with scrollIntoView

### ISSUE THREAD

**Issue by evgvis** [asmyshlyaev177/react-horizontal-scrolling-menu#174]
**Describe the bug**
window is scrolling without possibility return it back

**To Reproduce**
please open [codesandbox](https://codesandbox.io/s/basic-example-forked-kjl7k?file=/src/index.tsx)
its base example with changed a bit Footer component. now it has min-width 120vw and i commented position.
than, please click button Right and window will be scrolled instead of scrolling menu. now button Left will be outside of window

**Expected behavior**
should be scrolled only scrolling menu.

**Additional context**
some bug explanation https://stackoverflow.com/a/65955689

**Comment by asmyshlyaev177** [comment]
Hi.
With `.scroll` need to rewrite a lot, thinking `boundary` from this library better https://www.npmjs.com/package/scroll-into-view-if-needed  .

120 vw mean 120% of virtual width, almost always horizontal scroll on page is undesirable, but will think how to fix it later.

**Comment by asmyshlyaev177** [comment]
Fixed in new version, check it out - `2.6.0`

**Comment by evgvis** [comment]
everything seems to be ok. thanks ;)
