### ISSUE TITLE
Left/Right buttons doen't work in IE11/Edge

### ISSUE THREAD

**Issue by zverexe** [asmyshlyaev177/react-horizontal-scrolling-menu#18]
Using ie11/edge user cannot switch between tabs

**Comment by zverexe** [comment]
@asmyshlyaev177 do you have any updates? You can reproduce this with the example from here https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/ opening in edge

**Comment by asmyshlyaev177** [comment]
I tried to fix it today, but no success.
Some issue with babel.

**Comment by zverexe** [comment]
I checked the code and find out that issue may be here:
itAfterEnd = trans => {
    const { alignCenter } = this.props;
    const { menuWidth, allItemsWidth, lastPageOffset } = this;
    
    return alignCenter
      ? trans < defaultSetting.translate && Math.abs(trans) > allItemsWidth - menuWidth + lastPageOffset
      : trans < defaultSetting.translate && Math.abs(trans) > allItemsWidth - menuWidth;
  };
because this part return false instead of number when click on right/left arrow

**Comment by asmyshlyaev177** [comment]
> I checked the code and find out that issue may be here:
> 
> ```
> itAfterEnd = trans => {
>     const { alignCenter } = this.props;
>     const { menuWidth, allItemsWidth, lastPageOffset } = this;
>     
>     return alignCenter
>       ? trans < defaultSetting.translate && Math.abs(trans) > allItemsWidth - menuWidth + lastPageOffset
>       : trans < defaultSetting.translate && Math.abs(trans) > allItemsWidth - menuWidth;
>   };
> ```
> because this part return false instead of number when click on right/left arrow

It must return boolean.

**Comment by asmyshlyaev177** [comment]
Made new version, must work now in Edge.
With IE 11 more complex, don't support it worth it.

**Comment by zverexe** [comment]
where is the problem in ie 11?

**Comment by asmyshlyaev177** [comment]
With code transpilation, babel etc.

вт, 30 окт. 2018 г., 22:49 zverexe <notifications@github.com>:

**Comment by zverexe** [comment]
I see. I need to support IE11 so probably I'll check other menu solution. Sorry
