### ISSUE TITLE
Can I get a .js example?

### ISSUE THREAD

**Issue by simonsantan** [asmyshlyaev177/react-horizontal-scrolling-menu#183]
Hello, I am using react js, not typescript. But I am getting some error when I copy your code from codeSandbox example. Can you help me by giving an example in .js

https://codesandbox.io/s/no-scrollbar-and-buttons-position-c3kn5?file=/src/index.tsx:1610-1620

**Comment by simonsantan** [comment]
@asmyshlyaev177 , Hi there, I need one help. Please help me?

**Comment by asmyshlyaev177** [comment]
Hi, you can just remove types code, it's not that different from JS.

**Comment by simonsantan** [comment]
But why not working when I remove types definition?

**Comment by asmyshlyaev177** [comment]
https://codesandbox.io/s/basic-example-js-khhj5?file=/src/index.js

**Comment by simonsantan** [comment]
One more things, I it support reverse scroll.
