### ISSUE TITLE
[BUG] => ItemsMap()

### ISSUE THREAD

**Issue by kylix31** [asmyshlyaev177/react-horizontal-scrolling-menu#184]
When re-render occurs in some component in a page, the class ItemsMap lost it references.

Before re-render: 
![image](https://user-images.githubusercontent.com/52262819/151577212-5d394e6b-0745-45de-ae89-860796d55c66.png)

After re-render:
![image](https://user-images.githubusercontent.com/52262819/151577355-ad2b9390-1f56-4cab-8be6-fad9d8a7d72b.png)

**Comment by asmyshlyaev177** [comment]
Won't fix, can't sacrifice performance for this.
