### ISSUE TITLE
Arrow left and arrow right are not working

### ISSUE THREAD

**Issue by Leonardll** [asmyshlyaev177/react-horizontal-scrolling-menu#185]
**Describe the bug**
The arrows are not working on click

**To Reproduce**
Link to https://codesandbox.io/s/rough-frost-1bfv9?file=/pages/_app.js where can see the bug or steps to reproduce the behavior:
1. Go to 'home page '
2. Click on 'property picture '
4. See error when clicking on arrow right or left 

**Expected behavior**
It should render the next image in a slide 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome 89, safari 14]
 - OS: [e.g. iOS 14.7]
 - Mobile device (eg iPhone, Galaxy etc)

**Additional context**
i am using next js.

**Comment by asmyshlyaev177** [comment]
Hi, can you check link to sandbox? It's doesn't exist or private.

**Comment by Leonardll** [comment]
sure i will uploaded it right away, i will let it there shortly because there my api there

**Comment by Leonardll** [comment]
https://codesandbox.io/s/old-wildflower-bc1pw
thanks for your help

**Comment by asmyshlyaev177** [comment]
> https://codesandbox.io/s/old-wildflower-bc1pw thanks for your help

Now get error 
```
Server Error
Error: Request failed with status code 429

This error happened while generating the page. Any console logs will be displayed in the terminal window.
````

**Comment by Leonardll** [comment]
i am having the same on my side, i don't know how and why. I am trying to fix it I will let you know when it is fixed

**Comment by Leonardll** [comment]
I have exceeded the number of call on this specific api.  i had to create a new one. Sorry about this. This is the new link for the sandbox.  https://codesandbox.io/s/peaceful-proskuriakova-4h0y5?file=/pages/_app.js

**Comment by Leonardll** [comment]
is the link working ok?

**Comment by asmyshlyaev177** [comment]
> is the link working ok?

Yes, will let you know later.

**Comment by Leonardll** [comment]
thank you :)

**Comment by asmyshlyaev177** [comment]
It's works, but there can be more issues https://codesandbox.io/s/loving-gauss-85zdy?file=/components/ImageScrollbar.js
Should be 'itemId' not 'itemID' and issues with image size, images should be smaller than Scroll container.

Probably this library unsuitable for your use case, sorry.

**Comment by Leonardll** [comment]
ok thank you much for your help
