### ISSUE TITLE
[BUG] Next.js `Link` component drag behavior

### ISSUE THREAD

**Issue by rizzrark** [asmyshlyaev177/react-horizontal-scrolling-menu#186]
**Describe the bug**

When the `ScrollMenu` item or `Card` component is wrapped in a Next.js `Link` components the Drag behavior is buggy. That is, when you drag and release the drag, the mouse cursor get sticked to a card or item in the `ScrollMenu`

**To Reproduce**
Wrap the `ScrollMenu` item or `Card` in a Next.js `Link` component

**Expected behavior**
Wen the mouse leave de item or card the Drag stops.

**Screenshots**
![image](https://user-images.githubusercontent.com/75039059/153721085-aa9b4a1b-289d-4d3b-8207-1da5c6540860.png)
![bug](https://user-images.githubusercontent.com/75039059/153722901-7030b135-5283-4dd9-994f-afbf64f4021d.gif)

**Comment by asmyshlyaev177** [comment]
Not a bug with library, `a` elements draggable by default.
Apply css to `a` elements:
```
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
  user-drag: none;
```

**Comment by rizzrark** [comment]
I forked this [sandbox ](https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-drag-by-mouse-o3u2t?file=/src/index.tsx) and added the styles you recommended, and everything worked as expected.
