### ISSUE TITLE
Arrows are not Working

### ISSUE THREAD

**Issue by niichuu** [asmyshlyaev177/react-horizontal-scrolling-menu#187]
**Describe the bug**
Arrows ar not working

**To Reproduce**
Go to: https://codesandbox.io/s/drag-by-mouse-forked-h49sew?file=/src/index.tsx

**Expected behavior**
Arrows work

**Screenshots**
It's on sandbox

**Desktop (please complete the following information):**
Does not matter

**Additional context**
Thanks!

**Comment by asmyshlyaev177** [comment]
`itemId` for items should be unique.

**Comment by niichuu** [comment]
Thansk.

Reviewing my code y realized that i was wrapping all my singles objects into one div.
The itemId was a copy paste problem.

Anyway it help me to see my problem.
Thanks by your prompt answerd
