### ISSUE TITLE
What is <Arrow></Arrow>[BUG]

### ISSUE THREAD

**Issue by juliancstrocodes** [asmyshlyaev177/react-horizontal-scrolling-menu#189]
**Describe the bug**
When using the code example in the github, I am struggling with using the Arrow component which is not imported and is not a native feature in React.js.

**Expected behavior**
Should run without asking to import 'Arrow.'

**Desktop (please complete the following information):**
 - macOS: 12.1

**Comment by asmyshlyaev177** [comment]
Hi, can you provide more context or example?
Because if you don't need arrows you can just don't use them.
