### ISSUE TITLE
Center after click drag

### ISSUE THREAD

**Issue by niichuu** [asmyshlyaev177/react-horizontal-scrolling-menu#190]
**Is your feature request related to a problem? Please describe.**
It is possibl to center item after click & drag? it would have a nice smoot efect.
Lookin the examples i saw sparated solutions but not all in one.
Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asmyshlyaev177** [comment]
Hi, can try like this https://codesandbox.io/s/center-items-on-click-drag-e8cyph?file=/src/index.tsx
Changes in `Index` and in `card` files, follow `NOTE`

Is it what you want?

**Comment by niichuu** [comment]
Yes! Exactly that!
Thanks u!
