### ISSUE TITLE
Uglify JS throwing an error  Unexpected character '`'

### ISSUE THREAD

**Issue by kalyan542** [asmyshlyaev177/react-horizontal-scrolling-menu#193]
In the wepack `devtool: 'hidden-source-map'`

getting error when i do `yarn run build:admin`

```
ERROR in app-bundle-112fbf.js from UglifyJs
Unexpected character '`' [app-bundle-112fbf.js:38433,1169]
```

**Comment by asmyshlyaev177** [comment]
What do you mean? I don't have `yarn run build:admin` script and build works.

**Comment by kalyan542** [comment]
Sorry, May be i didn't explain the issue.
 
Issue is not with `yarn run build:admin`

In the webPack if i provide `devtool: 'hidden-source-map'` causing the issue
https://webpack.js.org/configuration/devtool/

**Comment by asmyshlyaev177** [comment]
I think better to use other plugin for minification
https://stackoverflow.com/questions/44287584/how-to-minify-es6-code-using-webpack
https://github.com/webpack-contrib/terser-webpack-plugin
