### ISSUE TITLE
Failed to minify the code error while build the app

### ISSUE THREAD

**Issue by DelliBabuG** [asmyshlyaev177/react-horizontal-scrolling-menu#195]
**Describe the bug**
When build the react code after added this package i am getting the "Failed to minify the code from this file ./node_modules/react-horizontal-scrolling-menu/dist/index.umd.js:1:1105" error, I am not able to proceed the build.

In local this package is working fine, When I try to build the code for production this issue is coming.

My React JS Version is - 16.13.1

@asmyshlyaev177 Please help me to resolve this issue, This feature is really looking nice for my application

**Screenshots**
![image](https://user-images.githubusercontent.com/58594975/166684759-36b9098c-7eb1-4713-b8ad-4235ae0b2668.png)

**Comment by asmyshlyaev177** [comment]
Works with default CRA.

You need to check which uglifier/minifier used, e.g. uglifyJS, Terser or something else.
Have 2 options:
 - Transpile this library with babel before minifier
 - Use other minifier

Need to see you webpack config(if custom used) and CRA version(if used)

**Comment by DelliBabuG** [comment]
@asmyshlyaev177 Thanks for the quick response

I haven't used the custom webpack config in my project, and here is my package.json file for your reference

{
  "name": "marketplace",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "antd": "^4.6.6",
    "aws-sdk": "^2.893.0",
    "axios": "^0.26.1",
    "bootstrap": "^4.5.0",
    "classnames": "^2.3.1",
    "connected-react-router": "^6.8.0",
    "firebase": "8.10.0",
    "flexslider": "2.7.1",
    "flow-bin": "^0.60.1",
    "font-awesome": "^4.7.0",
    "json-as-xlsx": "^2.3.10",
    "lodash": "^4.17.15",
    "qrcode.react": "^1.0.1",
    "quagga": "^0.12.1",
    "react": "^16.13.1",
    "react-countdown": "^2.3.2",
    "react-dom": "^16.13.1",
    "react-ga": "^3.1.2",
    "react-google-maps": "^9.4.5",
    "react-horizontal-scrolling-menu": "^2.7.1",
    "react-image": "^2.4.0",
    "react-localize-redux": "^2.15.1",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "1.0.17",
    "react-slick": "^0.28.1",
    "react-speech-recognition": "^3.8.2",
    "reactstrap": "^8.4.1",
    "redux": "^4.0.5",
    "redux-form": "^8.3.5",
    "redux-thunk": "^2.2.0",
    "slick-carousel": "^1.8.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "start-windows": "cross-env react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "flow-init": "flow init"
  },
  "devDependencies": {
    "cross-env": "^5.1.3"
  }
}

**Comment by asmyshlyaev177** [comment]
Can you try to upgrade `react-scripts` , eg `yarn add  react-scripts@2` / `npm install react-scripts@2`

**Comment by DelliBabuG** [comment]
@asmyshlyaev177 After I upgraded "react-scripts" from "1.0.17" to "2.0.3" its is working fine now, I can able to build my code and it is perfectly working in production environment.

Thanks a lot @asmyshlyaev177
