### ISSUE TITLE
[BUG] Warning: Invalid DOM property `itemId`. Did you mean `itemID`?

### ISSUE THREAD

**Issue by webceyhan** [asmyshlyaev177/react-horizontal-scrolling-menu#196]
**Describe the bug**
Warning: Invalid DOM property `itemId`. Did you mean `itemID`?

`
export const ImageScrollbar = ({ data }) => {
    return (
        <ScrollMenu LeftArrow={LeftArrow} RightArrow={RightArrow} key="itemID">
            {data.map((item) => (
                <Box
                    key={item.id}
                    itemID={item.id}
                    width="910px"
                    overflow="hidden"
                    p="1"
                >
                    <Image
                        placeholder="blur"
                        blurDataURL={item.url}
                        src={item.url}
                        width={1000}
                        height={500}
                        alt="property"
                        sizes="(max-width: 500px) 100px, (max-width: 1023px) 400px, 1000px"
                    />
                </Box>
            ))}
        </ScrollMenu>
    );
};
`

**Comment by asmyshlyaev177** [comment]
Just ignore the warning, `itemId` is correct.
