### ISSUE TITLE
Add support for adding component eg(title) prefix to the arrows

### ISSUE THREAD

**Issue by Preshonyee** [asmyshlyaev177/react-horizontal-scrolling-menu#197]
**Is your feature request related to a problem? Please describe.**
Right now, it's hard to add a component to the far left of the arrows. In an ideal use case, a title is almost always on the left hand side of the arrows. This would be a good addition.

**Describe the solution you'd like**
Something like Airbnb has it
![CleanShot 2022-05-10 at 08 50 47@2x](https://user-images.githubusercontent.com/19210093/167577541-073a35ae-cf0d-4a18-b249-3f48805dcb1e.png)

**Describe alternatives you've considered**
I've tried hacking together a CSS solution but it's not perfect still

**Comment by asmyshlyaev177** [comment]
Good issue, I will think how to implement it.

**Comment by Preshonyee** [comment]
@asmyshlyaev177 I attempted to fix this quickly for a live project as I couldn't wait for a PR to get merged.  Maybe you can take a look https://github.com/Preshonyee/react-horizontal-scrolling-menu 

Once you have a fix for this, I can un-publish the one I have and use your update. Thanks so much for creating this library. It has saved me a ton of work.

**Comment by asmyshlyaev177** [comment]
@Preshonyee Hi, i'm release a new version(2.8.2) and an [example](https://codesandbox.io/s/arrows-with-additional-content-0fhrm3?file=/src/index.tsx)

**Comment by Preshonyee** [comment]
> @Preshonyee Hi, i'm release a new version(2.8.2) and an [example](https://codesandbox.io/s/arrows-with-additional-content-0fhrm3?file=/src/index.tsx)

This is looking good really. Can you make the `additionalContent` a prop of type `ReactNode` or `JSXElement` so the user can pass any component with whatever styles to it without having to hack the layout with CSS?

For example, let's say I want to add a sub-heading(paragraph) under the `Additional Content` I would still have to hack it's layout position with CSS.

**Comment by asmyshlyaev177** [comment]
> > @Preshonyee Hi, i'm release a new version(2.8.2) and an [example](https://codesandbox.io/s/arrows-with-additional-content-0fhrm3?file=/src/index.tsx)
> 
> This is looking good really. Can you make the `additionalContent` a prop of type `ReactNode` or `JSXElement` so the user can pass any component with whatever styles to it without having to hack the layout with CSS?
> 
> For example, let's say I want to add a sub-heading(paragraph) under the `Additional Content` I would still have to hack it's layout position with CSS.

But still will need css for any additional content, right now arrows positioned with css also.
I think it's ok, by default no need to change css, but for additional content need css.

Maybe i can think of some prop like `arrowsPosition` = 'top|bottom|aside`, what do you think?

**Comment by asmyshlyaev177** [comment]
But also if user put arrows on top and use additional content need to use css again for position arrows above/bellow content.
So not sure about this.

**Comment by Preshonyee** [comment]
> > > @Preshonyee Hi, i'm release a new version(2.8.2) and an [example](https://codesandbox.io/s/arrows-with-additional-content-0fhrm3?file=/src/index.tsx)
> > 
> > 
> > This is looking good really. Can you make the `additionalContent` a prop of type `ReactNode` or `JSXElement` so the user can pass any component with whatever styles to it without having to hack the layout with CSS?
> > For example, let's say I want to add a sub-heading(paragraph) under the `Additional Content` I would still have to hack it's layout position with CSS.
> 
> But still will need css for any additional content, right now arrows positioned with css also. I think it's ok, by default no need to change css, but for additional content need css.
> 
> Maybe i can think of some prop like `arrowsPosition` = 'top|bottom|aside`, what do you think?

Exactly. I was just about to say the same. This way it can be really composable, rather than allow using CSS and classes to reposition the arrows, make the arrows part of the component api then allow a prop for changing its layout. Eg `arrowPosition` - `top, side, bottom, center`. etc.  and also a prop for giving it a prefix component....What do you think of this?

**Comment by Preshonyee** [comment]
> But also if user put arrows on top and use additional content need to use css again for position arrows above/bellow content. So not sure about this.

I think when the arrow is on top, the arrows can only be at the far right. Additional content can be at the far left and can be any component. The arrows only need to be aligned center, top, or bottom vertically related to the additional content on the left.

**Comment by asmyshlyaev177** [comment]
> make the arrows part of the component api 
Then it won't be so composable, will need to add more props and make it more complex.

> I think when the arrow is on top, the arrows can only be at the far right.
I thought similar about many things, but people come and ask for something new.

Just trying make library modular and customizable as much as possible, so no need to overcomplicate library for many rare use cases.

Will think about arrows position prop, but can't promise anything. If it goes too complex will leave it as is.

**Comment by Preshonyee** [comment]
I think a good way to judge the direction for where to add new features and composability would be to look at real world use cases on a large scale. Airbnb is a pretty good example. Large ecommerce sites too are some examples that use this at scale.

**Comment by Preshonyee** [comment]
> > make the arrows part of the component api
> 
> Then it won't be so composable, will need to add more props and make it more complex.
> 
> > I think when the arrow is on top, the arrows can only be at the far right.
> 
> I thought similar about many things, but people come and ask for something new.
> 
> Just trying make library modular and customizable as much as possible, so no need to overcomplicate library for many rare use cases.
> 
> Will think about arrows position prop, but can't promise anything. If it goes too complex will leave it as is.

Just thought of this now...Can you make the composability this way?
`<ScrollMenuHeader />`
`<ScrollMenuBody />`
`<ScrollMenuFooter />`
`<ScrollMenuSider />`

This way the arrows can either be on top (Header), bottom (Footer) or side (Sider). Either the `Header`, `Footer`, or `Sider` can contain the arrows. Otherwise the user can pass `null` to it. This way the additional content can also be on top, bottom, or side too.

I think this is a very good way to make it composable. What do you think of this?

**Comment by asmyshlyaev177** [comment]
> 
> Just thought of this now...Can you make the composability this way? `<ScrollMenuHeader />` `<ScrollMenuBody />` `<ScrollMenuFooter />` `<ScrollMenuSider />`
> 
> This way the arrows can either be on top (Header), bottom (Footer) or side (Sider). Either the `Header`, `Footer`, or `Sider` can contain the arrows. Otherwise the user can pass `null` to it. This way the additional content can also be on top, bottom, or side too.
> 
> I think this is a very good way to make it composable. What do you think of this?

This interesting idea, could be `Header` and `Footer`, Sider is just arrows on sides similar to how it works now.
I will try to implement this.

**Comment by Preshonyee** [comment]
Okay 😎...let me know how it goes. I can jump in and help too.

**Comment by asmyshlyaev177** [comment]
@Preshonyee Created draft version of PR, you can take a look and contribute if you like to.

**Comment by asmyshlyaev177** [comment]
Implemented in a new version.
