### ISSUE TITLE
How to run example?

### ISSUE THREAD

**Issue by IDriuk** [asmyshlyaev177/react-horizontal-scrolling-menu#199]
Hi! Library is great. Could you tell me please how to run example on windows 10.

 I've tried run

git clone https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu
yarn install
yarn run demo

 but got errors 

PS C:\Users\Ivan\react-horizontal-scrolling-menu> yarn install
yarn install v1.22.1
[1/4] Resolving packages...
success Already up-to-date.
$ yarn link-react
yarn run v1.22.1
$ rm -rf node_modules/react && rm -rf node_modules/react-dom && cd example-nextjs/node_modules/react && yarn link && cd ../react-dom && yarn link && cd ../../../ && yarn link react && yarn link react-dom && rm -rf node_modules/react && rm -rf node_modules/react-dom
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\Ivan\react-horizontal-scrolling-menu>

**Comment by asmyshlyaev177** [comment]
Didn't test it in windows environment, better to run it in [WSL](https://docs.microsoft.com/en-us/windows/wsl/)

Or can just form some example from codesandbox.

**Comment by asmyshlyaev177** [comment]
Also can install library for nextjs example.
