### ISSUE TITLE
Does it provide `snap` feature?

### ISSUE THREAD

**Issue by mshakhriyorov** [asmyshlyaev177/react-horizontal-scrolling-menu#203]
I am not sure if `react-horizontal-scrolling-menu` does support snapping feature. If yes, please, let me know it

**Comment by asmyshlyaev177** [comment]
Hi, can you give an example how it looks like?

**Comment by mshakhriyorov** [comment]
https://user-images.githubusercontent.com/71601329/173045646-02903b29-787c-40c0-af8b-bb6aafc65822.mp4

here is snap means that once you scroll mouse, item doesn't wait you to scroll to the end and snaps to the edge of layout

**Comment by asmyshlyaev177** [comment]
Maybe animation will do, not sure, https://codesandbox.io/s/custom-transition-animation-n2pyn

**Comment by mshakhriyorov** [comment]
> Maybe animation will do, not sure, https://codesandbox.io/s/custom-transition-animation-n2pyn

Thanks. But I guess, it's worth to add this feature
