### ISSUE TITLE
Multiple Menus in a page

### ISSUE THREAD

**Issue by chidraEl** [asmyshlyaev177/react-horizontal-scrolling-menu#204]
**Describe the bug**
I wanted to put many Horizontal menus in one page but only the last one works! Is there maybe a way to do that. i tried to work around the code and search other solutions. one of the old versions worked where u pass arrows directly without writing a function to tell it how the arrows work, but with the new version it's not working!

**Comment by asmyshlyaev177** [comment]
I need example to reproduce bug, for now it seems like working 
https://codesandbox.io/s/basic-example-2-components-ymlhtr?file=/src/index.tsx

**Comment by chidraEl** [comment]
[asmyshlyaev177](https://github.com/asmyshlyaev177)

Thank you for your reply! I found an example such as the one you gave me, the thing is you are using react 16 and I used react 18
So i'm working on a movies app and I'm sending movies data to HorizontalScrollbar.js to show as a react-horizontal-scrolling-menu

**This is the HorizontalScrollbar.js**

`import React,{useContext} from 'react'
import {Box, Typography} from '@mui/material'
import {ScrollMenu, VisibilityContext} from 'react-horizontal-scrolling-menu'
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import ArrowCircleLeftIcon from '@mui/icons-material/ArrowCircleLeft';
import MovieCard from './MovieCard'


const LeftArrow = () => {
    const {isFirstItemVisible,scrollPrev} = useContext(VisibilityContext);
    return (
        <ArrowCircleLeftIcon alt='Previous' disabled={isFirstItemVisible} onClick={() => scrollPrev('smooth')} className='right-arrow'/>
    )
}
const RightArrow = () => {
    const {scrollNext} = useContext(VisibilityContext)
    return (
        <Typography onClick={()=> scrollNext()}
            className='left-arrow'>
                <ArrowCircleRightIcon alt='Next'/>
        </Typography>
    )
}


  
function HorizontalScrollbar( {data}) {
    
  return (
    <>
    {data ?
        <ScrollMenu
            LeftArrow={LeftArrow}
            RightArrow={RightArrow}
            dragging={true}
            sx={{pl:{md:'100px',sm:'5px'}}}
            >
            {data.map( (item) => (
            <Box key={item.id}
                itemId={item.id}
                title={item.title}>
                <MovieCard data={item} />
            </Box>
            ))}
        </ScrollMenu>
    : 'NO MOVIES FOUND!' }
    </>
  )
}


export default HorizontalScrollbar`

**Comment by asmyshlyaev177** [comment]
I still need example on codesandbox or similar to reproduce it.
