### ISSUE TITLE
Click item scrolling not work

### ISSUE THREAD

**Issue by syamsanur** [asmyshlyaev177/react-horizontal-scrolling-menu#207]
**Describe the bug**
after click item scrolling not work.

**To Reproduce**
https://codesandbox.io/s/inspiring-bird-xvycgo?file=/src/App.js

1. click one of the item
2. try left or right button
3. Scroll not work

**Expected behavior**
after or before click the scroll function work as intended

**Comment by asmyshlyaev177** [comment]
It happening because you pass `itemId` prop as a number, expected a string.
Published 3.1.1 version where `itemId` always converted to string.
