### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by 1pedro** [asmyshlyaev177/react-horizontal-scrolling-menu#213]
**Is your feature request related to a problem? Please describe.**
I have a fixed size of items, but i want that the user thinks that is infinite or it's a loop.

**Describe the solution you'd like**
A prop named like `shouldLoop` that indicates that after the last item it should restart showing the first ones.

**Comment by asmyshlyaev177** [comment]
Can only make it scroll to last item after first one visible, something like this https://codesandbox.io/s/loop-scroll-4w8ek6?file=/src/arrows.tsx .

But can't make it seamless infinite loop.
