### ISSUE TITLE
The scrollable view isn't restricted when scrolling. It scrolls the entire page

### ISSUE THREAD

**Issue by PhillipMwaniki** [asmyshlyaev177/react-horizontal-scrolling-menu#214]
**Describe the bug**
Using v3.2.0
The scrollable area, when implemented, doesn't restrict the scrollable viewport. It instead scrolls the entire page. I installed v2.7.0 and noticed that it behaves correctly compared to the current version.

**Desktop (please complete the following information):**
 - Browser Edge 105
 - OS: MacOS Big Sur 11.6.6
 - Mobile device Laptop

**Additional context**
None

**Comment by asmyshlyaev177** [comment]
Need example of a bug in CodeSandbox or similar service.

**Comment by asmyshlyaev177** [comment]
Check out how it implemented in example https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-basic-example-swg0y?file=/src/usePreventBodyScroll.ts
