### ISSUE TITLE
Styling of arrow buttons

### ISSUE THREAD

**Issue by kiranrega** [asmyshlyaev177/react-horizontal-scrolling-menu#215]
**Styling for right and left arrow class names ?**
I have feature suggestion there is no class name for the right and left arrows. If this question is not valid please let me know. because I have stared react recently. 
Thank you

**Comment by asmyshlyaev177** [comment]
No need props to style arrows. You can style them any way you want, take a look at example https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-basic-example-swg0y?file=/src/arrows.tsx

**Comment by sunmoon-idegu** [comment]
@asmyshlyaev177 
The package wrap the customized left arrow and right arrow inside a div with class name:
react-horizontal-scrolling-menu--arrow-left and react-horizontal-scrolling-menu--arrow-right, which makes the customized position failed. Can you help?

**Comment by AlexSmyshlyaev-sm** [comment]
If you wanna put arrows on top/bottom can use `Header` or `Footer` props like in example https://codesandbox.io/s/no-scrollbar-and-buttons-position-c3kn5?file=/src/index.tsx:1415-1421
