### ISSUE TITLE
[BUG] RTL only scrolls 1 item at a time in Firefox

### ISSUE THREAD

**Issue by dkilgore-eightfold** [asmyshlyaev177/react-horizontal-scrolling-menu#216]
**Describe the bug**
RTL only scrolls 1 item at a time in Firefox.

**To Reproduce**
1. Open Firefox
2. Go to https://codesandbox.io/s/rtl-8lix35?file=/src/index.tsx
3. Click on the arrow button to scroll
4. See Items only scroll 1 at a time

**Expected behavior**
The behavior should be the same as ltr using group scroll. scrolling the group (not only 1 item)

**Comment by asmyshlyaev177** [comment]
Tnx for reporting, will fix.

**Comment by asmyshlyaev177** [comment]
Sorry for the delay, for now just monkey patching but it should work - https://codesandbox.io/s/rtl-ng3bq9?file=/src/index.tsx
