### ISSUE TITLE
[BUG] - Right arrow takes a long time to appear, cutting the content.

### ISSUE THREAD

**Issue by WilliamGMota** [asmyshlyaev177/react-horizontal-scrolling-menu#218]
When resizing the browser window, cut the last card and the right arrow doesn't show, it's necessary resize more to show arrows.

**To Reproduce**
1. Open link demo in Google Chrome [https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/](url)
2. Remove some cards, keep 3
3. Resizing slowly to the final edge of the last card
4. See the right arrow doesn`t show

Note: The problema happen in the first arrow in some situations, when resizing browser.

**Expected behavior**
Arrows must show immediately when resizing browser

**Screenshots**
![image](https://user-images.githubusercontent.com/48607040/207620751-a0c4a821-4955-4057-b2ba-614a27453377.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome Versão 108.0.5359.99 (Versão oficial) 64 bits]
 - OS: [Windows 11]

**Additional context**

To solve the problem I include two separators, one at the beginning and one at the end. I don`t know it`s the better approach.

In MenuItems.tsx 

```
  return (
    <>
      {childArray.map((child, index: number) => {
        const id = getItemId(child);
        const separatorId = id + separatorString;
        const isFirstItem = index === 0;

        return [
          isFirstItem && (
            <Separator
              className={separatorClass}
              id={id + "-f" + separatorString}
              refs={refs}
              key={id + "-f" + separatorString}
              index={index + -0.1}
            />
          ),
          <Item
            className={itemClass}
            id={id}
            key={'menuItem__' + id}
            refs={refs}
            index={index}
          >
            {child}
          </Item>,
          itemsCount > 1 && (
            <Separator
              className={separatorClass}
              id={separatorId}
              refs={refs}
              key={separatorId}
              index={index + 0.1}
            />
          ),
        ];
      })}
    </>
  );
```

**Comment by asmyshlyaev177** [comment]
Can't reproduce it for now. Try to update to latest version and better to record video with bug.
