### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sahalsajjad** [asmyshlyaev177/react-horizontal-scrolling-menu#22]
Do you have plans to add typescript support ? Primarily, there are two ways - 

1. Adding the project to DefinitelyTyped project so that users can have typescript support by installing `@types/react-horizontal-scrolling-menu`
2. Adding type declaration files (`.d.ts`) in this project itself.

If you are ready to merge a PR to add the declaration files to this repo itself, I can volunteer.

**Comment by asmyshlyaev177** [comment]
Hello, didn't think about TS, but if it not change much can add it.

If You can make PR with TypeScript support I will merge it asap.

**Comment by asmyshlyaev177** [comment]
Added typescript support.
