### ISSUE TITLE
Content Security Policy (CSP)

### ISSUE THREAD

**Issue by iamsuzeet** [asmyshlyaev177/react-horizontal-scrolling-menu#227]
are there any ways for configuring the content security policy ?
![image](https://user-images.githubusercontent.com/36234903/221539601-9da3eeac-1b16-4795-a446-1c50e9449236.png)

**Comment by asmyshlyaev177** [comment]
Hm, styles already in CSS, but rollup bundling it all in js.
End up with tweaking rollup config so styles will be in separate css file. Should fix this issue.
But now need to import styles separately, e.g.
```
//...
import { ScrollMenu, VisibilityContext } from 'react-horizontal-scrolling-menu';
import 'react-horizontal-scrolling-menu/dist/styles.css';
//...
```
