### ISSUE TITLE
[BUG] scrollPrev/scrollNext causes page to horizontally scroll

### ISSUE THREAD

**Issue by sinchang** [asmyshlyaev177/react-horizontal-scrolling-menu#230]
**Describe the bug**
as the title, it only doesn't work on RTL mode 

**To Reproduce**
[Link to codesandbox where can see the bug or steps to reproduce the behavior:](https://codesandbox.io/s/rtl-forked-wkxwp5?file=/src/header.tsx)

**Expected behavior**
shouldn't trigger page-level scroll

**Screenshots**
real project screenshot

https://i.imgur.com/e11FKz9.gif

**Desktop (please complete the following information):**
 - Browser [chrome 111.0.5563.64]
 - OS: [macOS 13.2.1]

**Additional context**

**Comment by asmyshlyaev177** [comment]
Sorry for the delay.
Can set try to set `noPolyfill={false}` or disable scroll on parent element when scroll menu focused.
Can't really fix it rn cause it is bug in polyfill that used.
