### ISSUE TITLE
Import goes wrong when importing from `type: "module"` node script

### ISSUE THREAD

**Issue by marcelgerber** [asmyshlyaev177/react-horizontal-scrolling-menu#232]
**Describe the bug**
Thanks for your great work on this library!
Our application is importing `react-horizontal-scrolling-menu` from NodeJS, because we're doing some server-side rendering.
However, in switching over to using ES modules, we are now getting import errors caused by this library.

**To Reproduce**
Link to replit where can see the bug or steps to reproduce the behavior:
1. Go to https://replit.com/@MarcelGerber/react-horizontal-scrolling-menu#index.js
2. Notice how the `index.js` is a simple ESM import of the library, and that the package.json specifies `type: "module"`
3. Click on "Run"
4. See error: 

```
file:///home/runner/react-horizontal-scrolling-menu-node-import/index.js:1
import { ScrollMenu, VisibilityContext } from 'react-horizontal-scrolling-menu';
         ^^^^^^^^^^
SyntaxError: Named export 'ScrollMenu' not found. The requested module 'react-horizontal-scrolling-menu' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-horizontal-scrolling-menu';
const { ScrollMenu, VisibilityContext } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

**Expected behavior**
The import should work just fine.

**Additional context**
It's always tough to debug how Node is resolving imports, but I think what's going on is this:
- Node goes through your `exports` and takes the first one that applies, i.e. this one: https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/ecf63afc228d25e46e2c1dba73119c748c60efe2/package.json#L20
- However, since you haven't specified `type: "module"` in your package.json, it assumes that this export is CommonJS, and tries to load it as CommonJS.

**How this can be fixed**
I think the easiest and most compatible fix would be to rename your dist assets:
Instead of generating `dist/index.umd.js` and `dist/index.esm.js`, instead name them `dist/index.cjs` and `dist/index.mjs`, which signals to all consumers of these files (including node) that they are CJS and ESM files, respectively.

**Comment by asmyshlyaev177** [comment]
Hi, tnx for reporting.
Tried your suggestion, but seems like it didn't solve problem https://replit.com/@AlieksandrSmyshliaiev/react-horizontal-scrolling-menu-node-import#package.json

If you can help debug this will be great, branch - https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/tree/232

**Comment by marcelgerber** [comment]
Thank you!
