### ISSUE TITLE
[BUG] Typescript error when I have multiple children under ScrollMenu

### ISSUE THREAD

**Issue by chinhoe** [asmyshlyaev177/react-horizontal-scrolling-menu#236]
**Describe the bug**
Typescript error appears when you have multiple children under ScrollMenu

**To Reproduce**
[Codesandbox](https://codesandbox.io/s/center-items-on-click-drag-forked-l3o0bf?file=/src/index.tsx)
![image](https://user-images.githubusercontent.com/15047293/233529313-c09a13d9-e774-46b5-98f0-049f1868215f.png)

**Expected behavior**
No typescript error

**Comment by asmyshlyaev177** [comment]
Hi, it is typescript issue, types in library are fine.
Can solve it using `Fragment`
```
              <>
                <Card
                  title="Test"
                  itemId="Test"
                  key="Test"
                  onClick={handleItemClick('Test')}
                  selected={isItemSelected('Test')}
                />
                {items.map(({ id }) => (
                  <Card
                    title={id}
                    itemId={id} // NOTE: itemId is required for track items
                    key={id}
                    onClick={handleItemClick(id)}
                    selected={isItemSelected(id)}
                  />
                ))}
              </>
```

Will update docs.

**Comment by asmyshlyaev177** [comment]
Looks like it is limitation on typescript right now, it's can't detect type of children correctly https://github.com/microsoft/TypeScript/issues/21699?ref=arahansen.com

Can just use `@ts-ignore`
