### ISSUE TITLE
[BUG] RTL with loop

### ISSUE THREAD

**Issue by sinchang** [asmyshlyaev177/react-horizontal-scrolling-menu#241]
see the demo https://codesandbox.io/s/loop-scroll-forked-yxkskw?file=/src/index.tsx

We can't click the left arrow button in RTL mode.

Appreciate it if we could add the demo about RTL with the loop feature

**Comment by asmyshlyaev177** [comment]
Sorry for the delay, I will look into it. But this requires writing better tests and possibly complex refactoring.
Can try to pass `noPolyfill` option, there is issue with it lib that used https://github.com/scroll-into-view/scroll-into-view-if-needed/issues/993
