### ISSUE TITLE
Failed to minify the code error while build the app  after react script update to   Version >=2  , build done but not running on production

### ISSUE THREAD

**Issue by bytebrigadecode** [asmyshlyaev177/react-horizontal-scrolling-menu#243]
i have one old project on react 16.14.0  and react-scripts:"1.1.1"
at the time of start no error and runing fine , on stagging it working fine
but when i am trying to build the project it giving error:

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-horizontal-scrolling-menu/dist/index.umd.js:1:140

Now as  a soulution i try with almost every posible  react-horizontal-scrolling-menu version but issue same.

Build not getting created

-------------------------------
Then i update the react-scripts:"1.1.1"  to 3.4.1 then build created but when upload the code on production and test giving error 

play:133     GET http://example.com/static/js/bundle.js net::ERR_ABORTED 404
play:133     GET http://example.com/static/js/0.chunk.js net::ERR_ABORTED 404
play:133     GET http://example.com/static/js/main.chunk.js net::ERR_ABORTED 404
---------

{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "1.4.3",
    "@material-ui/icons": "2.0.1",
    "axios": "0.18.0",
    "humanize-duration-es6": "^1.0.1",
    "i18next": "^11.3.3",
    "image-compressor.js": "^1.1.4",
    "lodash": "^4.17.5",
    "prop-types": "^15.6.1",
    "react": "^16.14.0",
    "react-collapsible": "^2.8.3",
    "react-dom": "^16.14.0",
    "react-ga": "^2.5.3",
    "react-horizontal-scrolling-menu": "^2.0.6",
    "react-html-parser": "^2.0.2",
    "react-i18next": "^8.3.8",
    "react-medium-image-zoom": "^3.0.13",
    "react-player": "^1.7.0",
    "react-redux": "^7.2.5",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "2.0.3",
    "react-slick": "^0.23.2",
    "react-swipeable-views": "^0.12.16",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "styled-components": "^3.1.6",
    "uuid": "^3.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

![image](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/132006615/66d01f7f-4b9a-49d8-9884-9aeb9419e237)

**Comment by AlexSmyshlyaev-sm** [comment]
Hi, am I understand right that with CRA 3 it's running locally and compelling?
Maybe CRA3 just put dist output in different folder? Need to check their upgrade guide.

Recently I upgraded CRA to version 5 in old project, some minor issues but everything works.
