### ISSUE TITLE
Could not find a declaration file for module 'react-horizontal-scrolling-menu'.

### ISSUE THREAD

**Issue by carlmuluba** [asmyshlyaev177/react-horizontal-scrolling-menu#245]
**Describe**
By Upgrading Dependencies to React 17.0.2 and up

**Message**
ModuleNotFoundError
Could not find module in path: 'react/jsx-runtime' relative to '/src/arrows.tsx'

**Comment by asmyshlyaev177** [comment]
Check out this sandbox https://codesandbox.io/s/react-horizontal-scrolling-menu-v2-basic-example-swg0y?file=/src/index.tsx
All deps updated to latest versions, no such problems.

So issue somewhere in your build config.
