### ISSUE TITLE
Vertically Scrolling Feature

### ISSUE THREAD

**Issue by martingg88** [asmyshlyaev177/react-horizontal-scrolling-menu#248]
The current version support scrolling vertically?

**Comment by asmyshlyaev177** [comment]
I will create some sandbox example.

**Comment by martingg88** [comment]
sure. thanks.

**Comment by asmyshlyaev177** [comment]
Basic idea is something like this https://codesandbox.io/s/basic-example-forked-v8c2lp?file=/src/index.tsx
All by css, other example how to tweak arrows with css https://codesandbox.io/s/no-scrollbar-and-buttons-position-c3kn5?file=/src/index.tsx

**Comment by martingg88** [comment]
many thanks

**Comment by asmyshlyaev177** [comment]
Added storybook example in [253](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/pull/253)
