### ISSUE TITLE
Incorrect scrolling width counting

### ISSUE THREAD

**Issue by zverexe** [asmyshlyaev177/react-horizontal-scrolling-menu#25]
When menu initially loading, width of scrolled items incorrectly counted. Scrolling area is too big, I scroll until blank space is visible wihtout any menu items. 
When I click on one of the menu items, it works correctly and blank area isn't visible
Also, mounted is false on initial load

**Comment by asmyshlyaev177** [comment]
Hi, need check a few things:

1. Is width of menu items changing after page load? For example if menu item contain image thus image will load after JS bandle and DOM ready, or maybe CSS stylesheet loaded after bandle.
2. Do you have last version? If not try a fresh one.
3. If previous steps didn't help need reproduce issue on [codesandbox](https://codesandbox.io/)

**Comment by zverexe** [comment]
1) no I don't use images
2) using latest version
3) I will try but not sure it will help
Also, when I dynamically upload number on items, arrows hide when can be in one row but when there a lot of items again, arrows didn't become visible

**Comment by zverexe** [comment]
okay, I fixed my bug by setTimeout(() => this.onLoad(), 200); but not sure that it is good solution

**Comment by zverexe** [comment]
but still I have bug when arrows didn't become visible once items quantity bigger then menu area. I cheched the code and found the issue that     const arrowsVisible = mounted ? this.isArrowsVisible() : true; didn't update properly when I change quantity of items(that happend when user types something and based on that items are updated).

**Comment by asmyshlyaev177** [comment]
Hm, i changed check for new items, now it will check more strict. Try new version.

**Comment by zverexe** [comment]
the problem is that in:
updateWidth = ({ items = this.menuItems }) => {
    const { alignCenter } = this.props;
    const width = this.getWidth({ items });
    console.log(width)
    return { ...width, ...(alignCenter ? this.getPagesOffsets({ items, ...width }) : {}) };
  }
width of all items updated correctely, on every menu items update but in:
isArrowsVisible = () => {
    const { allItemsWidth, menuWidth, props: {hideArrows} } = this;
    const hide = Boolean(hideArrows && allItemsWidth <= menuWidth);
    console.log(allItemsWidth)
    return !hide;
  };
didn't update on every items changes. It's like something block code running. updateWidth running but isArrowsVisible no. If I set this.forceUpdate in updateWidth, arrow visibility updated corretely(components re render and isArrowsVisible working correctely)

**Comment by asmyshlyaev177** [comment]
It is strange, code for hide/show arrows runs in every update, so need reproduce it.

**Comment by asmyshlyaev177** [comment]
Check out new version and is this bug still happen?
