### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by sleonia** [asmyshlyaev177/react-horizontal-scrolling-menu#250]
Hello!
I suppose that since the beginning of this this month we should do something about the situation in the Middle East, maybe even add something to readme. What do you think?

https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/commit/5fcfa758f487a0519d71be76019eb598764b3908#

**Comment by asmyshlyaev177** [comment]
Can add more badge or two, probably https://www.israelgives.org/ . I will check about that tomorrow.

**Comment by gavrilikhin-d** [comment]
> we should do something about the situation in the Middle East, maybe even add something to readme

Now this is an Avengers level threat.
