### ISSUE TITLE
[BUG]To many rerenders

### ISSUE THREAD

**Issue by cristea2017** [asmyshlyaev177/react-horizontal-scrolling-menu#258]
**Describe the bug**
On drag list we have a lot of unused rerender

pkg version : 
"react-horizontal-scrolling-menu": "^4.1.1",
"next": "^12.3.4",

**To Reproduce**
1. use demo code 
2. add wdyr @see- [https://github.com/welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render)

**Expected behavior**
- avoid rerenders

**Screenshots**

https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/28201006/5e8093a3-6251-437d-96a3-f0ed1504ff59

**Desktop (please complete the following information):**
 - Browser [Version 120.0.6099.129 (Official Build) (arm64)]
 - OS: [ macOs]

**Additional context**
related to 
https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/71

I guess that #71 doest help ) 

PS: thanks in advance

**Comment by cristea2017** [comment]
@asmyshlyaev177 

idk why , but if wrapping items in div rerenders disappear 🤷 🤯
```
  return (
    <ScrollMenu>
      <div style={{display: 'flex'}}>
        {items.map(({id}) => (
          <Card
            itemId={id} // NOTE: itemId is required for track items
            title={id}
            key={id}
            onClick={handleClick(id)}
            selected={isItemSelected(id)}
          />
        ))}
      </div>
    </ScrollMenu>
  );
```

**Comment by asmyshlyaev177** [comment]
@cristea2017 I will take a look, but can't promise anything.
Performance was ok last time I checked.

**Comment by asmyshlyaev177** [comment]
@cristea2017 Tested it, can't reduce numbers of rerenders further. With 6x CPU slowdown, it's still fast enough.
[rhsm-perf-2024-01-11_05.30.43.webm](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/19854148/820211bc-28ac-41be-b8e6-3834244f0e57)

React always rerender everything many times, better look on FPS count and CPU/memory usage.
