### ISSUE TITLE
How to prevent to scroll on scroll menu position when scrollPrev or scrollNext called.

### ISSUE THREAD

**Issue by alirezabakhshii** [asmyshlyaev177/react-horizontal-scrolling-menu#276]
Hi ! I want to  implement a feature using this package and i want to slide my content automatically by an interval but when i called scrollPrev and scrollNext functions my page is scrolling to scroll menu section.

Code Example :

useEffect(() => {
    const interval = setInterval(() => {
      if (!disabled && !isLastItemVisible) {
        scrollNext();
      }
    }, 4000);
    return () => clearInterval(interval);
  }, [disabled, isLastItemVisible, scrollNext]);

**Comment by asmyshlyaev177** [comment]
Can track if scroll menu visible and start/stop scrolling based on that, like here with useInterseptionObserver hook https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-simple--simple

**Comment by alirezabakhshii** [comment]
@asmyshlyaev177 Thank you so much it was very useful!
