### ISSUE TITLE
Scroll item to center but don't scroll the whole page so the item is in view.

### ISSUE THREAD

**Issue by nzmnisam** [asmyshlyaev177/react-horizontal-scrolling-menu#277]
**Is your feature request related to a problem? Please describe.**
I'm not frustrated, just asking if it's possible. Maybe I've missed something in the docs.

**Describe the solution you'd like**
I have an image row in a slideshow, like so
![image](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/63671525/db1e1f2a-bbc0-4ecd-baa3-64a3854453e5)
I would like to center the currently selected image in a row, but cannot figure out how to keep the slideshow running with centered image without it scrolling the page to the image every time. 

**Describe alternatives you've considered**
Maybe not to scroll the image row at all if it's not in view, but keep the slideshow running.

**Comment by asmyshlyaev177** [comment]
Can you provide a code example?

**Comment by nzmnisam** [comment]
This is the function that handles scrolling, I'm using my own since it's similar to the one in the lib, but I had it already

`  const scrollImageIntoView = useCallback(() => {
    if (imageRefs.current) {
      imageRefs.current[activeIndex]?.scrollIntoView({
        inline: "center",
        block: "nearest",
        behavior: "smooth",
      });
    }
  }, [activeIndex]);

  useEffect(() => {
    if (isScrolling) scrollImageIntoView();
  }, [isScrolling, scrollImageIntoView]);`
  
  This is the relevant part of the component
  `          <ScrollMenu
            onMouseMove={handleDrag}
            onMouseDown={onMouseDown}
            onMouseUp={onMouseUp}
            onWheel={onWheel}
            scrollContainerClassName={`cursor-grab flex flex-row py-2 md:py-4 scrollbar-webkit-carousel`}
          >
            {images.map((image, index) => {
              return (
                <div
                  // @ts-ignore
                  ref={(imageRef) => populateImageRefs(imageRef, index)}
                  key={index}
                  className={`${
                    index > 0 &&
                    index < images.length - 1 &&
                    "pl-1 pr-1 lg:pl-5 lg:pr-5"
                  } ${index === 0 && "pr-1 lg:pr-5"}
                ${index === images.length - 1 && "pl-1 lg:pl-5"} min-w-max`}
                >
                  <div
                    className={`${
                      index === activeIndex
                        ? "border-red-50/90"
                        : "border-gray-10"
                    }   border-[3px] max-w-[100px] md:max-w-[150px] transition-all duration-500 cursor-pointer`}
                    onClick={() => {
                      onClick(index);
                    }}
                  >
                    <Image
                      draggable={false}
                      src={image}
                      alt={`Image no${index + 1}`}
                      width={250}
                      height={200}
                    />
                  </div>
                </div>
              );
            })}
          </ScrollMenu>`



I've implemented to only scroll images into view once the user scrolls to the Images Row div, and to stop the scroll once the Images Row leaves the view.

**Comment by asmyshlyaev177** [comment]
`scrollIntoView` will always scroll element into view.
Can detect if whole block is visible on the page with hooks like this https://usehooks-ts.com/react-hook/use-intersection-observer

**Comment by nzmnisam** [comment]
Yeah, I got that. I already have the hook that servers that purpose. I was just wondering if it was possible to let it run in the "background", without scrolling the Y axis.
