### ISSUE TITLE
Issue with scroll on grab - div doesn't stop scrolling once the cursor exits scrollable area [BUG]

### ISSUE THREAD

**Issue by nzmnisam** [asmyshlyaev177/react-horizontal-scrolling-menu#278]
**Describe the bug**
div doesn't stop scrolling once the cursor exits scrollable area

**To Reproduce**
Link to a screen record of current behavior 
https://drive.google.com/file/d/1-P_HNjL2vVBBE_I-rW9qaC0N_GVShpUU/view?usp=drive_link

Code
- ScrollMenu component
![image](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/63671525/391f09c9-2339-432a-a607-669ca3571331)

- Mouse event functions
![image](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/63671525/d949d355-5033-4e3a-8be4-bd9c088bd89e)

**Expected behavior**
If the user is grab scrolling the div, while the left click is still down, user moves the mouse from the div and returns it, the div doesn't automatically continue to scroll. I think that this could be achieved if the component ScrollMenu had an onMouseLeave prop so that we could pass appropriate behavior to it.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - OS: win 11
 - Mobile device: not tested

**Comment by asmyshlyaev177** [comment]
Published v7.1.0 with `onMouseLeave` prop.

**Comment by nzmnisam** [comment]
Works perfectly, thank you
