### ISSUE TITLE
[BUG] Scroll doesn't work when the hight of Cards are higher than viewport

### ISSUE THREAD

**Issue by neginqantas** [asmyshlyaev177/react-horizontal-scrolling-menu#279]
**Describe the bug**

In storybook for Simple example set the hight of card by changing height: '200px', to height: '1200px',
Then click on right arrow. It doesn't scroll.
The isFirstItemVisible or isLastItemVisible return incorrect values when the hight of card is higher than viewport

**To Reproduce**
Link to codesandbox where can see the bug or steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome 89, safari 14]
 - OS: [e.g. iOS 14.7]
 - Mobile device (eg iPhone, Galaxy etc)

**Additional context**

**Comment by asmyshlyaev177** [comment]
Hi, can pass options to IntersectionObserver like `options={{ ratio: 0.5 }}`. In general, no sense to have items bigger than viewport.

**Comment by neginqantas** [comment]
Thanks for your reply. There is no option to set the threshold for VisibilityContext ( the OnScreenContext is not controlled by library) but the "isLastItemVisible" is coming from VisibilityContext
