### ISSUE TITLE
Use my own buttons and call forward/backward via refs?

### ISSUE THREAD

**Issue by artemisIrelia** [asmyshlyaev177/react-horizontal-scrolling-menu#28]
Does this component allow me to use my own arrow functions? Somewhere outside the div itself and call its forward/backward actions. 

I want the arrow buttons to be above the scrolling div. Apart from this great component and I am loving it.

**Comment by artemisIrelia** [comment]
Thanks this is just what I wanted. Would help a lot of people to have this info in the docs.

**Comment by asmyshlyaev177** [comment]
I updated readme.
