### ISSUE TITLE
Is it impossible to use it in the server component?

### ISSUE THREAD

**Issue by wherehows** [asmyshlyaev177/react-horizontal-scrolling-menu#280]
Thank you for providing a great library.

**Is your feature request related to a problem? Please describe.**

When I try to use it in the server component, a createContext error occurs. Do I have to use 'use client' without exception?

**Additional context**

![image](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/81841082/6f1c7455-17ea-4907-acda-7e14370f7b39)

```javascript
import ContentCard, { ContentCardProps } from "@/components/Card/ContentCard";
import { ScrollMenu } from "react-horizontal-scrolling-menu";

export default function Home() {
  return (
    <>
      <ScrollMenu LeftArrow={<div>123</div>} RightArrow={<div>456</div>}>
        {CONTENT_CARDS_DUMMY.map((data, index) => {
          return <ContentCard key={index} {...data} />;
        })}
      </ScrollMenu>
    </>
  );
}
```

**Comment by asmyshlyaev177** [comment]
Hello. Yes, this library depends on the IntersectionObserver browser API and React Hooks.
