### ISSUE TITLE
[BUG] Show and Hide Button Arrows

### ISSUE THREAD

**Issue by mcaiza20** [asmyshlyaev177/react-horizontal-scrolling-menu#281]
**Describe the bug**
I have two carousels with the scroll but when I go down the page the arrows appear and disappear, it is a behavior that happens the same in your examples. How could I control that from the beginning they do not appear if they do not have more items on the scroll?

**To Reproduce**
Link to codesandbox where can see the bug or steps to reproduce the behavior:
1. put a scroll at the end of the page
2. Scroll down to scroll items

**Expected behavior**
If they do not have items they should not appear

**Screenshots**
<img width="899" alt="Captura de pantalla 2024-06-24 a la(s) 13 31 37" src="https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/65578044/28465ef1-81d1-4380-908d-28cf15ec0a4e">

<img width="760" alt="Captura de pantalla 2024-06-24 a la(s) 13 31 46" src="https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/assets/65578044/7a1878ef-2bf7-47b5-8427-bc55cda6b48a">

**Desktop (please complete the following information):**
 - Browser chrome 89, safari 14
 - OS: MAC 
 - Mobile device (eg iPhone, Galaxy etc)

**Comment by asmyshlyaev177** [comment]
Can hide arrows by default, and when items updated they will appear if there are scroll.
```
const isFirstItemVisible = visibility.useIsVisible('first', true);
const isLastItemVisible = visibility.useIsVisible('last', true);
```
Second value in `useIsVisible` is default value, e.g. before first update.

Will dig into it more tomorrow.
