### ISSUE TITLE
Docs are outdated (visibleElements and initComplete)

### ISSUE THREAD

**Issue by talia-storymaker** [asmyshlyaev177/react-horizontal-scrolling-menu#282]
https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/docs/docs--docs

visibleElements and initComplete have been removed, but are still in the docs.

**Comment by asmyshlyaev177** [comment]
Should be good now, just reused docs from README, I can't keep up with 2 versions of docs in different formats.
