### ISSUE TITLE
[BUG] Import package

### ISSUE THREAD

**Issue by ntmduyenUpmesh** [asmyshlyaev177/react-horizontal-scrolling-menu#283]
**Describe the bug**
I have just added this package. Could I be missing any dependency packages?

**Screenshots**
![image](https://github.com/user-attachments/assets/366c7b7d-3cb2-4108-b766-39b2e3e09020)

**Additional context**
react-horizontal-scrolling-menu: "7.1.1"
react: "^17.0.2"
typescript: "4.4.2"

**Comment by asmyshlyaev177** [comment]
@ntmduyenUpmesh describe how to get to this, no idea why you opened a file inside node_modules.

**Comment by ntmduyenUpmesh** [comment]
I built it and it failed, the log led me to this line @asmyshlyaev177 . 
Besides, i tries to use `const visibility = React.useContext<publicApiType>(VisibilityContext);` it also shows this error

<img width="760" alt="image" src="https://github.com/user-attachments/assets/056d809e-d479-4851-b7b0-0d4e88209866">

**Comment by asmyshlyaev177** [comment]
Can try to upgrade Typescript version, e.g. `npm install -D typescript@latest`

**Comment by ntmduyenUpmesh** [comment]
I tried but it didn't work. Now, I'm downgrading to version 4.1.4

**Comment by asmyshlyaev177** [comment]
Looks like some issue with build process, what do you use, Next/webpack/cra/other?
