### ISSUE TITLE
Use swipe in desktop

### ISSUE THREAD

**Issue by alirezabakhshii** [asmyshlyaev177/react-horizontal-scrolling-menu#285]
Hi , I have a question about swipe feature.
can we use this feature for desktop ? 
it works on mobile device and i want use swipe for desktop 
may you help me please ?

**Comment by alirezabakhshii** [comment]
i appreciate it  @asmyshlyaev177

**Comment by asmyshlyaev177** [comment]
@alirezabakhshii created example https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-swipedesktop--swipe-desktop 
Star repo and follow me on github, appreciate it.

**Comment by alirezabakhshii** [comment]
Thank you, it was very useful  @asmyshlyaev177
