### ISSUE TITLE
[BUG] Button randomly not triggering

### ISSUE THREAD

**Issue by shankiflang** [asmyshlyaev177/react-horizontal-scrolling-menu#286]
**Describe the bug**
I've just updated to version 7.1.3 and I now have random buttons that don't trigger the “onClick” event. When I click on them, sometimes it works, sometimes it doesn't. It seems to be fully functional on firefox but not on the chrome based browser.

I downgraded to version 7.1.0 and the error disappeared.

Any idea?

**Comment by shankiflang** [comment]
It will be difficult to share the code as it is a corporate code. I can give you a link with the visual but I can't share the code :/ and reproducing a similar code would be difficult.

**Comment by asmyshlyaev177** [comment]
> It will be difficult to share the code as it is a corporate code. I can give you a link with the visual but I can't share the code :/ and reproducing a similar code would be difficult.

I need anything to reproduce the bug. Can't fix it otherwise.

**Comment by austrafin** [comment]
Possibly related. The same thing happens to me as in this code sample: https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-simple--simple

1. Scroll all the way to the right.
2. Scroll down the page so that the scroll menu is almost visible (see the picture).
3. Click on the left button -> the right button is not working anymore.
4. Scroll all the way to the left and now neither of the buttons are working.
![image](https://github.com/user-attachments/assets/2f0dc5f3-99fe-4525-8928-aeefc24c3c7e)

**Comment by asmyshlyaev177** [comment]
Ok, I see the bug.

**Comment by asmyshlyaev177** [comment]
Released version 7.1.4, should work now, check it out. @shankiflang @austrafin

**Comment by austrafin** [comment]
> Released version 7.1.4, should work now, check it out. @shankiflang @austrafin

Thank! Works better now. There's still a slight problem where for example, if you have two scroll menus on top of each other, the bottom buttons are not working until you scroll down so that the whole scroll menu is visible.

**Comment by asmyshlyaev177** [comment]
> > Released version 7.1.4, should work now, check it out. @shankiflang @austrafin
> 
> Thanks! Works better now. There's still a slight problem where for example, if you have two scroll menus on top of each other, the bottom buttons are not working until you scroll down so that the whole scroll menu is visible.

Items should become visible at least 1 time to detect which is visible and which isn't.
You can try to adjust observer threshold, e.g. when item considered visible - 0.5 when more than 50% of item visible.
``` typescript
          <ScrollMenu
            options={{ threshold: 0.1 }}
          >
```

**Comment by austrafin** [comment]
> > > Released version 7.1.4, should work now, check it out. @shankiflang @austrafin
> > 
> > 
> > Thanks! Works better now. There's still a slight problem where for example, if you have two scroll menus on top of each other, the bottom buttons are not working until you scroll down so that the whole scroll menu is visible.
> 
> Items should become visible at least 1 time to detect which is visible and which isn't. You can try to adjust observer threshold, e.g. when item considered visible - 0.5 when more than 50% of item visible.
> 
> ```ts
>           <ScrollMenu
>             options={{ threshold: 0.1 }}
>           >
> ```

This does not fix the problem.

**Comment by asmyshlyaev177** [comment]
@austrafin There isn't real need to scroll if you can't see what you're scrolling.

**Comment by austrafin** [comment]
> @austrafin There isn't real need to scroll if you can't see what you're scrolling.

Yeah, but the scroll button doesn't work even if the content is almost fully visible.
