### ISSUE TITLE
[BUG]next button not working when screen small

### ISSUE THREAD

**Issue by fukemy** [asmyshlyaev177/react-horizontal-scrolling-menu#287]
Hi, I am using the sandbox to test: https://codesandbox.io/p/sandbox/loop-scroll-4w8ek6?file=%2Fsrc%2Findex.tsx%3A71%2C4

 I can not click to right button when set screen size like phone size, as you can see the picture below:
<img width="1512" alt="Ảnh màn hình 2024-09-12 lúc 11 18 23" src="https://github.com/user-attachments/assets/35339ff2-0529-47bc-bca1-1a6e477134ef">

Can you resize the screen and test it's again? Thanks

**Comment by asmyshlyaev177** [comment]
@fukemy Hi, this is expected, item should be smaller than screen to be visible.
Alternatively, can change visibility ratio:
```ts
<ScrollMenu
...
options={{ ratio: 0.5 }} // e.g. item is visible when at least half of it visible
/>

```
