### ISSUE TITLE
support size percent, not exactly size(px,...)

### ISSUE THREAD

**Issue by fukemy** [asmyshlyaev177/react-horizontal-scrolling-menu#288]
Hi, I tried to use percent size for item, eg: width: '70%', but it's break my layout, as all the item will show in the ScrollMenu. Can you help?

**Comment by asmyshlyaev177** [comment]
Can look into this example https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-oneitem--one-item .
Normally, items should have fixed width.
