### ISSUE TITLE
[BUG] When the menu isn't in view on page load the last item visibility is incorrect

### ISSUE THREAD

**Issue by christine-harvie** [asmyshlyaev177/react-horizontal-scrolling-menu#289]
**Describe the bug**
If the horizontal scrolling menu isn't in view when the page loads then there is often a problem with checking if the last item is visible. One of the earlier items in the list is considered the last item, and it checks the visibility of that item instead of the actual last item. This leads to situations where the right arrow isn't visible when it should be.

The issue seems to start with version 7.1.2. I was able to avoid it by going back to version 7.1.1.

**To Reproduce**
1. Modify this example https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/?path=/story/examples-simple--simple
2. Move the filler div above the menu.
3. Add `console.log(visibility.items.last())` in the RightArrow function.
4. Reload the page
5. Scroll down to the menu. The right arrow might not be visible, depending on browser width.
6. Check the log. The last item is showing as "test2" or "test3". The actual last item is "test9".

**Expected behavior**
The last item should be "test9" and the right arrow should be showing.

**Screenshots**
This is my local version with the reproduction steps. In this example the right arrow is disabled because the last item is "test2". 
<img width="1440" alt="Screenshot 2024-10-03 at 4 29 33 PM" src="https://github.com/user-attachments/assets/0146e164-41cd-47c5-9c6f-d70f195d75a8">

**Desktop (please complete the following information):**
 - Browser: Chrome 129.0.6668.59 and Safari 17.4.1 (19618.1.15.11.14)
 - OS: MacOS 14.4.1

**Comment by asmyshlyaev177** [comment]
Yeah, still a problem, will take a look tomorrow or on the weekend.
Can use `7.1.2` for now, not big changes anyway.

**Comment by asmyshlyaev177** [comment]
@christine-harvie Disabled scroll polyfill by default, it's produce elusive bugs in some cases.

Check out version `8.0.0`, tell me if this solving this problem.

Tnx for your feedback btw, it's really important.

**Comment by christine-harvie** [comment]
Thank you for looking into it!

Unfortunately version 8.0.0 does not seem to fix this issue when I tried it. I tested in my actual project and in a local version of the 0_Simple storybook. The last item is still showing as "test2" or "test3".

**Comment by asmyshlyaev177** [comment]
> Thank you for looking into it!
> 
> Unfortunately version 8.0.0 does not seem to fix this issue when I tried it. I tested in my actual project and in a local version of the 0_Simple storybook. The last item is still showing as "test2" or "test3".

Possible that console.log print staled values, will come back to it a little later.

**Comment by christine-harvie** [comment]
No, the arrow is also not working as expected with version 8.0.0. It's often disabled when it shouldn't be

**Comment by asmyshlyaev177** [comment]
@christine-harvie  Reverted recent changes for now, for `8.0.1`. It's working very differently on Chrome/Firefox.
Will need more time to investigate and fix the last issue.

Check out how it works now.

**Comment by christine-harvie** [comment]
Version 8.0.1 is working well for me in the modified storybook and my actual project. The right arrow is enabled at the correct times. Thank you so much for looking into this.

**Comment by asmyshlyaev177** [comment]
Release `v8.0.2`, even better.
