### ISSUE TITLE
Initial translate still using 51px when set as 0/-1

### ISSUE THREAD

**Issue by jiayimu** [asmyshlyaev177/react-horizontal-scrolling-menu#29]
Initial translate doesn't work when set it as 0 or -1.
        
    <ScrollMenu  
           data={data}  
           arrowLeft={ArrowLeft}  
           arrowRight={ArrowRight}  
           translate={0}  
           wheel={false}  
           selected={selected}  
           onSelect={onSelect}  
    />
        
Got the following html after refresh web page. 
`<div class="menu-wrapper--inner" style="width: 9900px; transform: translate3d(51px, 0px, 0px); transition: transform 0.4s ease 0s; white-space: nowrap; text-align: left; user-select: none;">`

**Comment by asmyshlyaev177** [comment]
Will fix it soon.
But better pass alignCenter={false} and translate will be 0.

**Comment by jiayimu** [comment]
After add `alignCenter={false}`, the translate works perfect.
