### ISSUE TITLE
Add scroll target control

### ISSUE THREAD

**Issue by Seras3** [asmyshlyaev177/react-horizontal-scrolling-menu#290]
**Is your feature request related to a problem? Please describe.**
In nested scroll containers the scrollIntoView is uncontrollable.

**Describe the solution you'd like**
See [this thread](https://github.com/w3c/csswg-drafts/issues/9452) and [this comment](https://github.com/w3c/csswg-drafts/issues/9452#issuecomment-1756829797) as a possible substitution for the scrollIntoView.

**Additional context**

https://github.com/user-attachments/assets/f4b9c709-d623-4928-be81-82cac980fbfc

**Comment by asmyshlyaev177** [comment]
Currently, I'm using a polyfill `smooth-scroll-into-view-if-needed`, can be enabled with `noPolyfill={false}`, it's from same author that `compute-scroll-into-view`, used internally as well.
But that polyfill also problematic, has bugs in some edge cases.
