### ISSUE TITLE
RTL alignment support

### ISSUE THREAD

**Issue by rabinmahato** [asmyshlyaev177/react-horizontal-scrolling-menu#32]
Does this component support RTL alignment? If supports please tell me the process.

**Comment by btargac** [comment]
hi @asmyshlyaev177,  I think @rabinmahato needed right to left support like I do now. Any plans to support RTL languages ?

**Comment by btargac** [comment]
I made a pull request by the way https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/pull/73
