### ISSUE TITLE
JavaScript module doesn't work as expected for usage with Gatsby

### ISSUE THREAD

**Issue by ajayns** [asmyshlyaev177/react-horizontal-scrolling-menu#33]
When using the library with Gatsby, the production build doesn't work when the it uses the `.mjs` file. Reverting back to the JS file fixes the issue.

**Comment by ajayns** [comment]
It shows a `Cannot read component from undefined` error.

**Comment by asmyshlyaev177** [comment]
is it work if just rename extension to .js?

**Comment by ajayns** [comment]
Removing this line https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/23111244dfdca55cc41f5bd8ee3782189c67f9cd/package.json#L6 seems to have fixed the issue

**Comment by ajayns** [comment]
Basically, it's some issue with the module version

**Comment by asmyshlyaev177** [comment]
Can you try just rename file and filename in package?

**Comment by ajayns** [comment]
I don't think it's a filename issue, but rather an issue cause of the different way a JS module is exported in comparison to a normal ES export. I will look into what could possibly be causing the issue when I get the time.

**Comment by asmyshlyaev177** [comment]
Mjs build it for old module exports, idea is have few version for better compatibility.

**Comment by asmyshlyaev177** [comment]
Don't know how to deal with it, for now removed "module" field from package.json.
