### ISSUE TITLE
onUpdate wrong behavior 

### ISSUE THREAD

**Issue by fyanezv** [asmyshlyaev177/react-horizontal-scrolling-menu#34]
When component receive `translate` prop  in initial mount, `onUpdate` callback is not executed. This is due of this condition: 

```javascript
if (onUpdate && translate !== translateOld && translate !== lastTranslateUpdate) {
```

Sometimes `translate` and `lastTranslateUpdate` are equals to `0`. So, If I remove the last part of the condition, then the behavior is the expected

```javascript
if (onUpdate && translate !== translateOld /*&& translate !== lastTranslateUpdate*/) {
```
I think that the condition `translate !== translateOld` is enough. 

Greetings from Chile!

**Comment by asmyshlyaev177** [comment]
I intensionally made component doesn't call onUpdate on mount, because translate can be passed as props.

**Comment by fyanezv** [comment]
This is an example:

Component is mounted passing prop `translate` with value `-640`.

Then if a perform a click on the left arrow `OnUpdate` receive the following values:

`translateOld -640` 
`translate 0` 
`lastTranslateUpdate 0`

`translate` and  `lastTranslateUpdate` are both `0`,  so `onUpdate` callback  is not called

**Comment by fyanezv** [comment]
Maybe initial value of `lastTranslateUpdate` must be `null`

**Comment by asmyshlyaev177** [comment]
Ok, will look about this issue tomorrow.

**Comment by fyanezv** [comment]
Can I perform a tiny PR? 

Currently with my team we are using this Component and we are very interested to contribute.

**Comment by asmyshlyaev177** [comment]
Sure.

**Comment by asmyshlyaev177** [comment]
I merged it, by the way found another bug.

**Comment by fyanezv** [comment]
How can I reproduce the new bug?

**Comment by asmyshlyaev177** [comment]
I made [issue](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/issues/37)
But this bug existed before your PR.

**Comment by asmyshlyaev177** [comment]
My mistake, forgot about flag scrollToSelected(default=false)
Can pass initial translate OR selected item, but not both same time.
