### ISSUE TITLE
Can i use a custom component as data

### ISSUE THREAD

**Issue by chamatt** [asmyshlyaev177/react-horizontal-scrolling-menu#38]
I would like to use this to make a horizontal scroll of Avatar images, instead of plain text, is this possible? If so, how? The examples I've seen all use the same data souce (a list of objects with name key).

Thanks in advance!

**Comment by asmyshlyaev177** [comment]
Hi, yes it is possible, somebody use it like this, just don't have example.

```
// can use list of images or get it from api
const list = [
  { address: 'http://someimage.jpeg' },
  { address: 'http://someimage2.jpeg' },
  { address: 'http://someimage3.jpeg' },
];
```

```
const Avatar = ({ address, selected }) => {
  return (
    <img
                    //change className depend on selected prop
                   // scrollMenu will pass selected
      className="menu-item"
      src={address}
    />
  );
};
```
```
// Array of any custom components
export const Menu = (list) => list.map(e => {
  const { address } = el;

  return (
    <Avatar
      address={address}
      key={address} //better use some ID or name for key
    />
  );
});
```

And pass it same way.
```
const menu = Menu(someProps);
...
<ScrollMenu
          data={menu} // Here
          arrowLeft={ArrowLeft}
          arrowRight={ArrowRight}
          selected={selected}
          onSelect={this.onSelect}
        />
```

Something like that, just add some styles to your images, you can fork example on codepen. 
Appreciate if you add example with images.

**Comment by chamatt** [comment]
Thanks for the help, i'll try that later.

The examples i was talking about were the ones that you made with text, not images, i couldn't find any example with images
