### ISSUE TITLE
Trying to test the examples but `npm install fails`

### ISSUE THREAD

**Issue by dryleaf** [asmyshlyaev177/react-horizontal-scrolling-menu#4]
I decided to clone your repository to try out some of the examples but on running `npm install`, execution fails. Below is the log of this:
```
D:\Samples>cd react-horizontal-scrolling-menu
D:\Samples\react-horizontal-scrolling-menu>npm install
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! code 1
npm ERR! Command failed: C:\cygwin\bin\git.EXE clone --mirror -q https://github.com/maicki/why-did-you-update.git C:\Users\admin\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-0dae8b53\.git --config core.longpaths=true
npm ERR! /cygdrive/c/Users/admin/AppData/Roaming/npm-cache/_cacache/tmp/git-clone-0dae8b53/C:\Users\admin\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-0dae8b53\.git: No such file or directory
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-08-15T23_33_32_311Z-debug.log
```

Also the examples:
```
D:\Samples\react-horizontal-scrolling-menu>cd examples

D:\Samples\react-horizontal-scrolling-menu\examples>npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:..

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-08-15T23_38_02_853Z-debug.log
```

How can this be fixed?

**Comment by asmyshlyaev177** [comment]
> `npm ERR! Command failed: C:\cygwin\bin\git.EXE clone --mirror -q https://github.com/maicki/why-did-you-update.git C:\Users\admin\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-0dae8b53\.git --config core.longpaths=true`
Ok, about this, npm can't isntall why-did-you-update directly from github, looks like windows bug. This package need only for development and only sometimes, can remove it from package.json. I think will remove it also soon.

Before i tried to use windows for work and found many problems with npm packages(node-sass for example), on linux or osx everything fine.
Better use Cygwin Terminal(shortcut must be in start menu), git bash cmd or [windows 10 linux subsystem ](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/).

> `D:\Samples\react-horizontal-scrolling-menu\examples>npm install`
My bad. Will update example, can fix it by remove this line from example package.json
    `"react-horizontal-scrolling-menu": "link:.."`
and run from examples directory
`npm install --save react-horizontal-scrolling-menu
npm install
npm run start`
