### ISSUE TITLE
Left arrow bug

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#40]
Hello, [check this example](https://codesandbox.io/s/7yv74z8l30) please

Seems to be there is something wrong with offset calculations when **alignCenter is false**

Steps to reproduce:
Click right arrow (it works)
Click left arrow (it doesn't)
Also note the position of the list, now click to any item in the list, it jumps to the beginning immediately.

![bug1](https://user-images.githubusercontent.com/1753208/52959740-ab674800-339f-11e9-9649-11384623e6c3.gif)
![bug2](https://user-images.githubusercontent.com/1753208/52959745-b326ec80-339f-11e9-96fa-144fffee69c6.gif)

Settings:
```
<ScrollMenu
    ref={el => (this.menu = el)}
    data={menu}
    arrowLeft={ArrowLeft}
    arrowRight={ArrowRight}
    onUpdate={this.onUpdate}
    onSelect={this.onSelect}
    alignCenter={false}
    wheel={false}
  />
      </div
```

**Comment by asmyshlyaev177** [comment]
Hi, bug with example or if try to change alignCenter after component mounted.
Tnx, will look later.

**Comment by asmyshlyaev177** [comment]
I updated example, will scroll to start, but arrows are working now.

**Comment by NeXTs** [comment]
Yes, in v0.5.0 it works fine, thanks!
