### ISSUE TITLE
Items are not centered when window width decreases

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#42]
[Please try here](https://codesandbox.io/s/pk9k31npj7)

When window width increases, elements are centered properly, it's ok.
But when window width decreases, elements are positioned slightly on left from center.

Demo:
![bug4](https://user-images.githubusercontent.com/1753208/52961716-419d6d00-33a4-11e9-8f6b-42bde6aed700.gif)

**Comment by asmyshlyaev177** [comment]
I'm thinking about maybe just make separate method for align items, but call it outside of component.
Can do normal debounce for example.

**Comment by asmyshlyaev177** [comment]
Maybe don't touch elements position on resize at all.
You can checkout rc branch if have time https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/tree/rc

**Comment by NeXTs** [comment]
In this case, items aren't centered after resize ¯\_(ツ)_/¯
Not a big deal, though

**Comment by asmyshlyaev177** [comment]
Can try prerelease version **0.5.7-0**
`npm install react-horizontal-scrolling-menu@0.5.7-0`

**Comment by NeXTs** [comment]
Hello! Yes, it works great in 0.5.7
