### ISSUE TITLE
Transition to initial position

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#43]
[Please check this link](https://codesandbox.io/s/qlxoq86804)

There is toggle button, click it few times.
You would notice that every time when lists appears, there is transition to initial position in the first list.
This transition reproduces with small amount of items, when full width of all items is smaller than viewport of list's width.
Second list does not have this transition.

![bug5](https://user-images.githubusercontent.com/1753208/52964020-f8501c00-33a9-11e9-9e89-5bd63bb8352e.gif)

It's very noticeable on my project because I use react-horizontal-scrolling-menu in rows that are rendered by ReactList. So every time I scroll the page, new react-horizontal-scrolling-menu elements renders and transition animation appears.
How do you think, is it possible to set initial position statically without transition?

---
btw in second list I've used
```
scrollToSelected
selected="item6"
```
and item 6 indeed appeared in the viewport, but not in center. This is not so important, just let you know.

**Comment by asmyshlyaev177** [comment]
2 ways for set initial position:
scrollToSelected and selected prop same you use
and use translate props.

But will look to your example, it doesn't seem right.

**Comment by asmyshlyaev177** [comment]
I made branch 43, you can check is it work as expected or not.

**Comment by NeXTs** [comment]
Thanks for the quick response to this
On branch 43 after page load elements remains in the beginning of the list. Although after any interaction with the page (for example window resize), elements are transitioned to the center.
My expectations were that after page load elements will be centered by default.

**Comment by asmyshlyaev177** [comment]
Seems like need refactor all this, code too cluttered, some decisions was not best.

**Comment by asmyshlyaev177** [comment]
Can you check now? Seems like it works ok.

**Comment by NeXTs** [comment]
Yes, elements are centered now

**Comment by asmyshlyaev177** [comment]
Please nothing else broken)
At least this issue can merge fast, refactor later.

**Comment by asmyshlyaev177** [comment]
Branch merged to master.

**Comment by pengw00** [comment]
> Thanks for the quick response to this
> On branch 43 after page load elements remains in the beginning of the list (on the left). Although after any interaction with the page (for example window resize), elements are transitioned to the center.
> My expectations were that after page load elements will be centered by default.

how did you resolve this, encounter same problem

**Comment by NeXTs** [comment]
> > Thanks for the quick response to this
> > On branch 43 after page load elements remains in the beginning of the list (on the left). Although after any interaction with the page (for example window resize), elements are transitioned to the center.
> > My expectations were that after page load elements will be centered by default.
> 
> how did you resolve this, encounter same problem

I didn't
