### ISSUE TITLE
How can i scroll just one item at a time?

### ISSUE THREAD

**Issue by Davinasc** [asmyshlyaev177/react-horizontal-scrolling-menu#45]
Hi !

I'm noob --'

I need to scroll just one item at a time, can i do that with a simple solution?

**Comment by asmyshlyaev177** [comment]
Right now can't, maybe will implement it as option, good idea.

**Comment by Davinasc** [comment]
Thanks for the feedback 😆

**Comment by asmyshlyaev177** [comment]
You can try prerelease version ### 0.5.7-0
Looks like it works, prop _scrollBy_ for that, 1/2/3 or 0 for default behavior

`npm install react-horizontal-scrolling-menu@0.5.7-0`

**Comment by asmyshlyaev177** [comment]
Added in new version - 0.5.7
