### ISSUE TITLE
Accessibility: No tab order for menu items

### ISSUE THREAD

**Issue by invot** [asmyshlyaev177/react-horizontal-scrolling-menu#47]
No tab order is assigned through the menu items. Could I suggest providing an option to render the menu items as buttons, links, or the current simple divs?

**Comment by asmyshlyaev177** [comment]
What exactly do you mean by that?

**Comment by invot** [comment]
For people who navigate web applications using their keyboard, they will "tab" through an interface, literally going from one interactive element (links, buttons, fields, etc) to the next. 

https://www.w3schools.com/tags/att_global_tabindex.asp

Making something tab-able means assigning a tabindex value to the element.  Some HTML elements have that assigned by default, but divs would need that placed manually.

**Comment by asmyshlyaev177** [comment]
So arrows can have tabindex 1-2 and other to menu items?

**Comment by invot** [comment]
The arrows likely should too, since it's an interactive element. I posted a pull request simply for the items in the menu: https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/pull/48

**Comment by asmyshlyaev177** [comment]
Can select menu items, but can't choose it with just tabIndex.

**Comment by invot** [comment]
exactly

**Comment by asmyshlyaev177** [comment]
What's a point then?

**Comment by asmyshlyaev177** [comment]
Can add handler for select menu item via spacebar|enter.

**Comment by invot** [comment]
The idea is that if you want someone using a keyboard to be able to use this component, you should add a tabindex attribute to the menu items so they can focus on them. You can read more about that here: https://developer.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/

One of the requirements of the software I'm building is that it's accessible. I can add the tabindex myself but I felt like it's something you might also want to make a feature by default. If not, that's fine, I can make my own branch, but I felt it made sense to tell you it's a functionality people may require.

**Comment by asmyshlyaev177** [comment]
Ok, i added it in new version.

**Comment by diogobas** [comment]
Talking about accessibility, is that possible to select an item by hitting enter/space bar? is this component prepared for that?

**Comment by pgdesjardins** [comment]
> Talking about accessibility, is that possible to select an item by hitting enter/space bar? is this component prepared for that?

Having the same issue. If you make the menuItems button it would work as it would trigger the wrapper click, sadly the wrapper.tsx:234 tabindex={0} prevent from focusing in the child button

I'm manually removing the tabindex in a useEffect and voila, you can focus on the menuItem button and use Enter to trigger it

Suggestion: provide an option to disable tabindex as the current implementation provides focus but does not handle the keyboard event, or have the wrapper handle keyboard event to make the selection

**Comment by asmyshlyaev177** [comment]
Can you check V2?
