### ISSUE TITLE
Refresh datasource

### ISSUE THREAD

**Issue by AlexBrgs** [asmyshlyaev177/react-horizontal-scrolling-menu#5]
When I give new data in props to ScrollMenu, the list was not refresh automatically. I find in your shoulComponentUpdate, if you add :

const {data} = nextProps;
menuItems !== data (in return)

, the refresh is done. (There is maybe an other method, I start with React ^^)

Moreover, if you do also the centering of elements (or reorder), this become great. In any case, your component is very useful and matches to my need !! ;)

**Comment by asmyshlyaev177** [comment]
I ma glad it useful)
Update data or at least selected item via props in plans, but now have much work to do at job.
Will implement this feature soon.

**Comment by asmyshlyaev177** [comment]
Made changes and now selected item and offset from props will update component state. With new data elements more complicated.

**Comment by NeXTs** [comment]
Just figured out this plugin doesn't support data elements update. I need it as well.
Any reason [it was](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/commit/6ca243c8701e682f2dbfa94b7123b1b7e6e6652b) made?

**Comment by asmyshlyaev177** [comment]
> Just figured out this plugin doesn't support data elements update. I need it as well.
> What was the reason [for this](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/commit/6ca243c8701e682f2dbfa94b7123b1b7e6e6652b)?

Commit about call on update, menu item can't be updated from start. Not so easy implement this feature.

**Comment by asmyshlyaev177** [comment]
Start implement this in branch datasource, but need more testing for now.

**Comment by asmyshlyaev177** [comment]
It is done, version 0.3.0. Please check how it works how.

**Comment by NeXTs** [comment]
Works like a charm, thank you!
