### ISSUE TITLE
Show scrollbar

### ISSUE THREAD

**Issue by samturner3** [asmyshlyaev177/react-horizontal-scrolling-menu#50]
Is there away to show the scrollbar to scroll through the items?
Is there a `-webkit-scrollbar ` property being set to `display:none` somewhere we can override, or would it be a custom react item programmed to reflect the current position of the menu?

**Comment by asmyshlyaev177** [comment]
It set to ```overflow: hidden``` in wrapper default styles. 
I will think how to implement this.

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0` there can show scrollbar.
