### ISSUE TITLE
Touchpad side scrolling

### ISSUE THREAD

**Issue by KurtBliss** [asmyshlyaev177/react-horizontal-scrolling-menu#51]
So the clickable arrows work fine to scroll and so does scrolling up and down on my touchpad.. 

But scrolling left and right on my touch pad i can only go right, if I go left i get pushed back right.. wonder how to fix it... 

i'm not even able to run the source by its self just to play around with it yet... 

not sure if somehow making the side buttons scroll too is breaking the ability to scroll left and right and a touchpad maybe or if your emulating a scroll bar and just haven't programed it

I'm really happy I found this almost works perfectly for me

**Comment by asmyshlyaev177** [comment]
I will try check it on xcode, in chrome it's works fine.

**Comment by KurtBliss** [comment]
I'm running chrome (Version 73.0.3683.86 64bit) on macOS Mojave 10.14.3...

![Screen Recording 2019-03-26 at 12 49 37 PM](https://user-images.githubusercontent.com/7538857/55040962-3374e900-5001-11e9-8fc8-8e455569ef3e.gif)

**Comment by asmyshlyaev177** [comment]
Also on macOS Mojave.
Can you check prerelease version**0.5.7-0**

**Comment by asmyshlyaev177** [comment]
It harder that i thought, on my laptops 2 finger scroll gesture detected as wheel event.

**Comment by KurtBliss** [comment]
Came up with an alternative with some jquery and css hopefully i don't have any issues putting this in react https://jsfiddle.net/15bxrc86/1 no click to drag though

**Comment by asmyshlyaev177** [comment]
But i scroll via js changing translate property and handle all events via react.
I thought about make it with scroll, but then can't set initial position for elements.

Will think how to do it later.
