### ISSUE TITLE
onClick Function

### ISSUE THREAD

**Issue by rank922** [asmyshlyaev177/react-horizontal-scrolling-menu#53]
Hi ,
I'm new with react. Is the onClick function active on this component? Because I have a series of buttons with the onClick function in the menuItem but my onClick function is not called.

**Comment by asmyshlyaev177** [comment]
Hi, i will look when have time.

**Comment by asmyshlyaev177** [comment]
Added in new version (0.5.8)
Original onClick from items should work.
