### ISSUE TITLE
Intertia scrolling for touch device

### ISSUE THREAD

**Issue by mozartatplay** [asmyshlyaev177/react-horizontal-scrolling-menu#54]
How easy would it be to implement inertia scrolling where you flick sideways and the items scroll first at fast and then slow down? Would be happy to help code this if you think its possible.

**Comment by NeXTs** [comment]
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/
https://css-tricks.com/almanac/properties/s/scroll-behavior/

**Comment by mozartatplay** [comment]
Tried this on my Android phone running Chrome v73. But still doesn't produce any inertia scrolling

<ScrollMenu style={{overflow: 'scroll', overflowX: 'scroll', WebkitOverflowScrolling: 'touch', scrollBehavior: 'smooth'}}
          data={menu}
          arrowLeft={ArrowLeft}
          arrowRight={ArrowRight}
          dragging={true}
          alignCenter={true}
          clickWhenDrag={false}
        />

**Comment by asmyshlyaev177** [comment]
Because this component use transform translate for change item position.

**Comment by mozartatplay** [comment]
Ok so inertial scrolling not possible? 

Maybe I should use a different horizontal scroller if I detect a mobile touch device. Netflix do this for example: On a standard browser they have a horizontal scroller with arrows and on a touch device they remove the arrows and do inertial scrolling.

**Comment by asmyshlyaev177** [comment]
Can try to implement it via js, but for now it's not possible.

**Comment by Entkenntnis** [comment]
inertia scrolling is an important feature for our product, so we implemented it, PR is availabe: #58

**Comment by asmyshlyaev177** [comment]
Thank you @Entkenntnis.
PR merged, new version 0.6.0.
