### ISSUE TITLE
There is no way to select items in single click

### ISSUE THREAD

**Issue by sitannsu** [asmyshlyaev177/react-horizontal-scrolling-menu#55]
How can i make the item clickable on single click rather then double click

**Comment by asmyshlyaev177** [comment]
Can you reproduce it?

**Comment by sitannsu** [comment]
Yes for me the items getting selected on double click everytime. On single click the item is not getting selected.

Thanks
Sitansu

**Comment by asmyshlyaev177** [comment]
I mean on codepen or somewhere.
