### ISSUE TITLE
How can I change default style?

### ISSUE THREAD

**Issue by Jongkeun** [asmyshlyaev177/react-horizontal-scrolling-menu#56]
First of all, thanks for your library.
I want to use this library, but I hope to remove default style.
Especially this.

![image](https://user-images.githubusercontent.com/33743343/57362289-70fc9280-71b9-11e9-8d84-04671edab6d4.png)

So I tried something to remove it 
```
  <ScrollMenu
        data={menu}
        arrowLeft={ArrowLeft}
        arrowRight={ArrowRight}
        selected={selected}
        menuStyle={null}
        wrapperStyle={null}
        alignCenter={false}
      />
```
and in css file
```
.menu-wrapper--inner {
  width: 100%
}
```

But it didn't work anything.
Is there any way to remove or modify default styles?

**Comment by asmyshlyaev177** [comment]
Can pass styles in wrapperStyle prop.
But, component will not work without _translate_ style or with _width 100%_.

**Comment by Jongkeun** [comment]
Really? 
That's a super bad news for me. 😭
Thank you for your quick reply.
