### ISSUE TITLE
Some Items (with relatively short height) gets lower

### ISSUE THREAD

**Issue by ingun37** [asmyshlyaev177/react-horizontal-scrolling-menu#57]
**Describe the bug**
Some items with relatively short height seems to align it's top on center.

![image](https://user-images.githubusercontent.com/3048481/58306723-70a9fb80-7e37-11e9-9f4d-33317ddc82ec.png)

Outmost wrapper doesn't seem to be oversized.

![image](https://user-images.githubusercontent.com/3048481/58307165-d21e9a00-7e38-11e9-9f07-62d1ae937284.png)

I tried to reproduce from your example. I tried giving items a random heights, I tried replacing items with [Material-Components-React-Card](https://github.com/material-components/material-components-web-react/tree/master/packages/card) just like in my project. But it worked fine in your example. I guess it's because of some subtle differences from my project. And I'm trying to figure it out.

Hopefuly you encountered similar issues and know what's happening?

**Desktop, Smartphone**
 - chrome, safari

**Comment by asmyshlyaev177** [comment]
Hello, seems like something with css styles, not with my component. Need recheck what styles applied to _menu-wrapper--inner_ _and menu-item-wrapper_
You can try to set height of _menu-item-wrapper_ to 100%.

**Comment by ingun37** [comment]
I was trying to reproduce in your example then I found this little confusing.

![image](https://user-images.githubusercontent.com/3048481/58315090-cab4bc00-7e4b-11e9-9c9c-20479690627c.png)

In first row I created random squares in new `ScrollMenu`.  It gets aligned on bottom.
In second row I set radom height to existing example items of `ScrollMenu`. It gets aligned on top.

I couldn't find any option related to this.  
I think my problem would be solved if I could align them in center.  
Is it possible?

FYI you can run the code in here [forked repository](https://github.com/ingun37/react-horizontal-scrolling-menu)

**Comment by asmyshlyaev177** [comment]
Not sure why it happening, but can fix in 2 ways:
- Change styles on inner-wrapper,  prop _innerWrapperStyle={ display: 'flex', alignItems: 'center'}_
- Add style to item wrapper, prop _itemStyle={verticalAlign: 'center'}_

**Comment by ingun37** [comment]
Thanks for update!
