### ISSUE TITLE
Scroll functionality not working when using images

### ISSUE THREAD

**Issue by AlberErre** [asmyshlyaev177/react-horizontal-scrolling-menu#6]
Hey there!

I've faced an issue while using images as items in the scroll menu - Basically, the elements (images) render perfectly, but both the scroll functionality and arrow buttons don't work.

**This behaviour is solved when I refresh the page.** - Any thoughts where this may come from?

I'm using a map() function to return each menu item (image).

P.S.
As I'm using map(), I could assume the initial array of elements being passed internally is just one item, the first one, this init array would be small enough to unable the scroll and arrow functionality. 
Then, the rest of the menu items are added by the map, but this init config get stuck until I refresh the page.

**Comment by asmyshlyaev177** [comment]
My guess - component detect item's width by _getBoundingClientRect_ , so if image didn't loaded and have width 0 can be problem. After page refresh images must be cached by browser, so maybe it available faster.

Can try set fixed images width via inline styles or CSS and see what happen.

**Comment by AlberErre** [comment]
Thank you!

Yep, **fixed width** on images has solved the issue :D, inline styling works perfectly.

As you suggested, "width" is not available until the image is completely loaded, which is an asynchronous task - should be great to implement a method to solved this internally.

**Comment by asmyshlyaev177** [comment]
For images maybe better use react-slick or something similar.
Can actually detect when image loaded 
https://reactjs.org/docs/events.html#image-events
https://www.javascriptstuff.com/detect-image-load/
