### ISSUE TITLE
how to remove active btn border

### ISSUE THREAD

**Issue by Wangzihao5325** [asmyshlyaev177/react-horizontal-scrolling-menu#60]
Thanks for your library!
I want to use this library, but how to remove active btn border:
<img width="339" alt="屏幕快照 2019-05-25 下午2 58 32" src="https://user-images.githubusercontent.com/20266841/58366535-eed0d580-7efd-11e9-8f12-951033ecf3d5.png">
just the yellow part

**Comment by Wangzihao5325** [comment]
the yellow part appeared when item was clicked,but it seems that it is not the item border.how can i remove it

**Comment by asmyshlyaev177** [comment]
Hi, can add **outline: none** to item wrapper to remove selection on focus.

**Comment by Wangzihao5325** [comment]
it works! thanks a lot!
add  **itemStyle={{ outline: 'none' }}** solve the problem
