### ISSUE TITLE
scrollToEndOfSelectedItem

### ISSUE THREAD

**Issue by BijayRai** [asmyshlyaev177/react-horizontal-scrolling-menu#61]
I am using this react-horizontal-scrolling-menu for my personal use and here i do have larger width items which does not fit in my wrapping bar. 

Here you guys already do have feature **scrollToSelected onSelect** it automatically scroll to the front of that particular item. 
![Screen Shot 2019-05-27 at 4 25 19 PM](https://user-images.githubusercontent.com/4888819/58415384-0050e380-809e-11e9-9fc3-6cbe6459472a.png)

But can we have feature on which we can directly scrollTo the end of the selected item??
![Screen Shot 2019-05-27 at 4 25 35 PM](https://user-images.githubusercontent.com/4888819/58415391-0646c480-809e-11e9-9dc6-5a17d53e0435.png)

Here link of [stackoverflow](https://stackoverflow.com/questions/56324615/scroll-to-the-end-of-item-react-horizontal-scrolling-menu)

**Comment by asmyshlyaev177** [comment]
Hello, just it was not intended that one menu item can be wider that whole menu container.
In this case problematic track visible items, from that depend much of logic.

You can try to get offset to next item with method **getOffsetToItemByKey('item2')** and subtract menu width (**$r.menuWidth**). Will be position where _item1_ ending visible.
