### ISSUE TITLE
Returning string 'null'

### ISSUE THREAD

**Issue by Whispers12** [asmyshlyaev177/react-horizontal-scrolling-menu#62]
If i pass to ur library null value, u return me "null"

https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/blob/6aaa980e518937dd55c44bd246a25318a1cd17fa/src/scrollMenu.tsx#L682-L689

Is there an explanation for this?

**Comment by asmyshlyaev177** [comment]
It's returning ```[ 'null', { key: 'n', elem: null, index: -1 },]``` empty object, if can't find item with passed key.

**Comment by asmyshlyaev177** [comment]
Can change it, but where exactly error or problem?

**Comment by Whispers12** [comment]
Thanks for quick response
https://codesandbox.io/s/sweet-surf-9t2bt
Look console.
If i pass null, i wanna get null, but i get 'null'

**Comment by asmyshlyaev177** [comment]
Can return empty string, for don't change typescript definitions.
Is '' fine?

**Comment by Whispers12** [comment]
It's a good idea.

**Comment by asmyshlyaev177** [comment]
Ok, in version 0.6.11
