### ISSUE TITLE
Cards snap back

### ISSUE THREAD

**Issue by haveamission** [asmyshlyaev177/react-horizontal-scrolling-menu#65]
**Describe the bug**
The items snap back immediately after I pull them

**To Reproduce**
I create a card in React and programmatically fill the list via componentDidMount()

I then cannot pull permanently over them.

**Example repo**
This is in cordova, I don't have a working example of the bug but I can implement one later

**Desktop (please complete the following information):**
Cordova - iOS

**Smartphone (please complete the following information):**
iPhone 8 and iOS simulator

**Comment by asmyshlyaev177** [comment]
Hi, need some example.

**Comment by haveamission** [comment]
Trying to get your library working in code pen, but whenever including it, I get an error about require, despite choosing Babel and including React.

https://codepen.io/haveamission/pen/KjwVNY

**Comment by asmyshlyaev177** [comment]
Can fork codeSandbox Demo on https://codesandbox.io/s/lpjol1opmq

**Comment by haveamission** [comment]
I forked it, still throwing an unrelated error.

https://codesandbox.io/s/react-horizontal-scrolling-menu-vbcrx

My guess is that this particular problem is due to my lack of understanding of JSX.

**Comment by haveamission** [comment]
This was due to adding cards to the state at different points - the width was not fixed and this caused some issues.

It works when I hold off rendering until all of the cards are present.

**Comment by asmyshlyaev177** [comment]
Ok, good. Maybe will update README.

**Comment by AwesomeIronman** [comment]
I had similar issue,
In my case using margins on menu-item-wrapper caused this bug,
so instead I add all my content inside another div
and gave padding to menu-item-wrapper
