### ISSUE TITLE
Method to increase scrolling speed

### ISSUE THREAD

**Issue by haveamission** [asmyshlyaev177/react-horizontal-scrolling-menu#66]
**Is your feature request related to a problem? Please describe.**
I feel the scrolling is a little slow in my implementation and would like a way to scale this speed

**Describe the solution you'd like**
A setting that lets you set a translation speed

**Comment by asmyshlyaev177** [comment]
`transition` props, 0.4 by default, try to set 0.2 for example.

**Comment by haveamission** [comment]
That doesn't seem to affect the speed by much. I have multiple cards, and I have to swipe multiple times to get through one.

Is there anyway I can override the transition speed to make it even faster?

**Comment by asmyshlyaev177** [comment]
It's strange, should scroll by width of all visible cards. Can be problem if only 1 card visible.
Can you reproduce it in codepen?

**Comment by haveamission** [comment]
I have noticed that scrolling by mouse scroll wheel is fast, but either dragging via mouse or by touch is slow.

I had trouble with doing a codepen example before, but I'll try to figure something out if I can.

**Comment by haveamission** [comment]
Ok, it's actually the difference between drag and scroll.

I may have to fork the library to add the functionality I want, which is a scroll-like effect using touch.

**Comment by haveamission** [comment]
One possible solution may be emulating wheel events. Doesn't seem to currently work, but I'll update this as I look for a possible workaround.

    var wheeleventLeft = new WheelEvent("wheel", {deltaY: -50});
    var wheeleventRight = new WheelEvent("wheel", {deltaY: 50});
    this.hammer.on('swiperight', () => window.dispatchEvent(wheeleventRight));
    this.hammer.on('swipeleft', () => window.dispatchEvent(wheeleventLeft));
    }

**Comment by haveamission** [comment]
Here's a code sandbox about it

https://codesandbox.io/s/react-horizontal-scrolling-menu-ij2yw
