### ISSUE TITLE
scrollToSelected not working

### ISSUE THREAD

**Issue by alexchomiak** [asmyshlyaev177/react-horizontal-scrolling-menu#67]
Whenever my selected item changes within the menu, the menu does not scroll to the selected item

**Comment by alexchomiak** [comment]
`import React, { Component } from 'react'
import {connect} from 'react-redux'
import './Carousel.scss'

import CarouselItem from './Carousel-Item/CarouselItem'
import ScrollMenu from 'react-horizontal-scrolling-menu'

const Arrow = ({ text, className }) => {
    return (
      <div
        className={className}
      >{text}</div>
    );
  };
   
   
  const ArrowLeft = Arrow({ text: '<', className: 'arrow-prev' });
  const ArrowRight = Arrow({ text: '>', className: 'arrow-next' });


class Carousel extends Component {
  
    onSelect = key => {
        this.setState({selected: key})
    }
    /*
    alignCenter: true,
    clickWhenDrag: false,
    dragging: true,
    hideArrows: true,
    hideSingleArrow: true,
    itemsCount: list.length,
    selected: "item1",
    translate: 0,
    transition: 0.4,
    wheel: true
    */

    render() {
        let indexOfCurrent = this.props.viewerstate.sceneNodes.indexOf(this.props.viewerstate.currentNode)
        let nodeArray = [...this.props.viewerstate.sceneNodes]
       

        return (
            <div className="carousel-container">
                <div className="carousel-list">
                    {
                        <ScrollMenu
                            data = {nodeArray.map((node) => {
                                return (
                                    
                                                  <CarouselItem active={this.props.viewerstate.currentNode === node} key={node.id} node={node}/>
                          
                                )
                            })}
                            selected={(this.props.currentNode !== undefined) ? this.props.currentNode.id : 10}
                            translate= {0}
                            transition = {0.4}

                            scrollToSelected
                            wheel = {false}


                        />
                    
                    }
                    
                </div>
            </div>
        )
    }
}


const mapStateToProps = (state) => {
    return {
        viewerstate: state.viewerstate,
        preferences: state.preferences
    }
}
export default connect(mapStateToProps)(Carousel)`

**Comment by asmyshlyaev177** [comment]
Hi, can you reproduce it on code sandbox and explain how it should work?

**Comment by alexchomiak** [comment]
Actually, I solved the issue and it scrolls to the element, but I have a css transition that resizes the selected element to make it larger, but there is a bug in which if that element is on the edge of the menu, it causes it to scroll back and forth like crazy and end up with that element out of view.

**Comment by asmyshlyaev177** [comment]
Can try increase padding for items in `itemStyle` or in your components, but will be some free space between elements.
