### ISSUE TITLE
Should drag and arrow click recompute all menu elements?

### ISSUE THREAD

**Issue by istanfield09** [asmyshlyaev177/react-horizontal-scrolling-menu#69]
Maybe I am not understanding React, or how this component works, but should every drag and arrow click result in recomputing all the elements in your menu?

Even in the codesandbox demo provided in the documention, I noticed that the `Menu` functional component on line 39 iterates through every item in the list repeatedly during drag events. Is there a way to stop this?

**Comment by asmyshlyaev177** [comment]
Can use pure CSS if performance is a concern. But will be less functionality.
Why do you worry about that?

**Comment by istanfield09** [comment]
Thanks for your response. I went ahead and made a put a CSS horizontal scrolling menu inside my react container when user is using mobile. I encountered these issues with mobile only, since dragging is the primary UX pattern in these menus on mobile devices. I'll close the issue.
