### ISSUE TITLE
hideArrows is not working

### ISSUE THREAD

**Issue by ittechsathish** [asmyshlyaev177/react-horizontal-scrolling-menu#70]
**Describe the bug**

**To Reproduce**

**Example repo**
Reproduction of bug in codepen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by asmyshlyaev177** [comment]
Please add description in what conditions it doesn't work, better reproduce on `codesandbox`
