### ISSUE TITLE
Frequent item rerenders on drag

### ISSUE THREAD

**Issue by YevheniiMelikov** [asmyshlyaev177/react-horizontal-scrolling-menu#71]
**Describe the bug**
If drag is enabled passed items components are rerendered on each drag event. Since it fires very frequently it causes major lag if card is something more complicated then text container.

**To Reproduce**
1. In example add console.log in MainItem render function.
2. Make sure drag is enabled.
3. Open example and drag items while looking at console
4. See the issue that item is rerendered frequently.

**Screenshots**
![Jul-05-2019 18-59-43](https://user-images.githubusercontent.com/13350594/60733984-17190e80-9f57-11e9-8397-42c546dc9f09.gif)
Each console log here is full list of items rerendered.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 75.0.3770.100 (Official Build) (64-bit)

**Comment by YevheniiMelikov** [comment]
Fixed it here
https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/pull/72

**Comment by asmyshlyaev177** [comment]
Merged.
