### ISSUE TITLE
Arrow left and arrow right are not working 

### ISSUE THREAD

**Issue by sauravgarg540** [asmyshlyaev177/react-horizontal-scrolling-menu#78]
**Describe the bug**
left arrow and right arrow are not working when page renders page also on reloading the page but starts working once browser is resized.

**Desktop (please complete the following information):**
 - Chrome

**Comment by asmyshlyaev177** [comment]
Need reproduce it on codesandbox.

**Comment by sauravgarg540** [comment]
Issue is resolved. Thanks for your time.
