### ISSUE TITLE
Scroll does not reach the end

### ISSUE THREAD

**Issue by SergeShkurko** [asmyshlyaev177/react-horizontal-scrolling-menu#79]
**Describe the bug**
Scroll does not reach the end

**Screenshots**
![ezgif-4-10cbf5499e92](https://user-images.githubusercontent.com/18213789/66701349-dc243500-ed14-11e9-8144-1b0ef25c2ec3.gif)

**Desktop (please complete the following information):**
 - Сhrome v77
 - Package v0.7.3

**Comment by asmyshlyaev177** [comment]
Does width of menu items changes after it passed to components?

**Comment by SergeShkurko** [comment]
@asmyshlyaev177 no, they have a predetermined width

**Comment by asmyshlyaev177** [comment]
Need to reproduce it on codepen.io

**Comment by SergeShkurko** [comment]
Example on codesandbox: https://codesandbox.io/s/practical-shape-rb5yf

The problem is that the size of the item is not defined correctly if I assign a class with margin to the itemClass attribute. If you remove the margin is determined normally

**Comment by asmyshlyaev177** [comment]
Can make wrap items in container, instead of margin use padding for it.

**Comment by asmyshlyaev177** [comment]
Can make wrap items in container, instead of margin use padding for it.

**Comment by SergeShkurko** [comment]
ok

**Comment by rotimi-best** [comment]
> Does width of menu items changes after it passed to components?

I have a use case where the width can change after it is mounted. I use this library for tabs and the tabs title can be edited. In this case I get the above issue where I can't scroll to the end nor the beginning. Any ideas on how to solve that?

**Comment by asmyshlyaev177** [comment]
> > Does width of menu items changes after it passed to components?
> 
> @asmyshlyaev177
> I have a use case where the width can change after it is mounted. I use this library for tabs and the tabs title can be edited. In this case I get the above issue where I can't scroll to the end nor the beginning. Any ideas on how to solve that?

Can't handle items that can change size for now. As a workaround can wrap tabs so only wrappers keep same size.
