### ISSUE TITLE
Swipe on mobile

### ISSUE THREAD

**Issue by ak1nak** [asmyshlyaev177/react-horizontal-scrolling-menu#80]
**Is your feature request related to a problem? Please describe.**

Right now on mobile devices swipe is really hard and uncomfortable, i think dragging is kind of it but no.

**Describe the solution you'd like**
On swipe event and swipeable prop = true, menu scrolled by items count in scrollBy.

**Additional context**

https://www.npmjs.com/package/react-responsive-carousel

swipeable | boolean | true | Enables swiping gestures

**Comment by asmyshlyaev177** [comment]
Can you try to use `inertiaScrolling` and `inertiaScrollingSlowdown` props for mobile devices?

**Comment by kumaraswamyDR** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Right now on mobile devices swipe is really hard and uncomfortable, i think dragging is kind of it but no.
> 
> **Describe the solution you'd like**
> On swipe event and swipeable prop = true, menu scrolled by items count in scrollBy.
> 
> **Additional context**
> 
> https://www.npmjs.com/package/react-responsive-carousel
> 
> swipeable | boolean | true | Enables swiping gestures

Facing the same issue on mobile phones

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0` there scroll on mobile works.
