### ISSUE TITLE
Center clicked item

### ISSUE THREAD

**Issue by Mohammedalasaad** [asmyshlyaev177/react-horizontal-scrolling-menu#81]
Hi,
Would be nice to have a feature when we click on item so it scroll it to center so other items easy to click then and clear that there is more items..

**Comment by fallenmel** [comment]
i have same issue? any work around on this?

**Comment by Mohammedalasaad** [comment]
I think now its working only if we click on item on right slide so it slide to left,, but if u click on left item it does not slide to right.. 
I use this:
`              <ScrollMenu
                    data={menu.props.children}
                    arrowLeft={ArrowLeft}
                    arrowRight={ArrowRight}
                    wheel={false}
                    alignCenter={false}
                    hideArrows={true}
                    hideSingleArrow={true}
                    scrollBy={2}
                    selected={this.state.selected}
                    onSelect={this.onSelect}
                    scrollToSelected={true}
                />`

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0`, it should works.
