### ISSUE TITLE
How can I make `word-wrap: break-word;` work properly for `itemStyle`

### ISSUE THREAD

**Issue by eliasturbay** [asmyshlyaev177/react-horizontal-scrolling-menu#84]
**Describe the bug**

I'm trying to use this component as the footer of another Video component, where the "menu" is a video playlist's thumbnails. The problem is that I want to use 3 lines for the video titles. But I cannot find a proper way to make it work :(

**To Reproduce**
```
              <ScrollMenu
                data={playlistItems.map((item, index) => (
                  <div key={index} className="playlist-item">
                    <div className="thumb">
                      <img src={item.image} alt="" />
                    </div>
                    <div className="desc">{item.title}</div>
                  </div>
                ))}
```

Styles:
```
.playlist-item {
  width: 148px;
  padding: 10px;
}

.thumb {
  overflow: hidden;
  height: 60px;
}

.thumb img {
  width: 100%;
  position: relative;
  top: -13px;
}

.playlist-item .desc {
  @include fontScale(-1);
  font-family: map-get($fonts, serif);
  color: #fff;
  line-height: 1.2em;
  overflow: hidden;
  word-wrap: break-word;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
}

.playlist-item:hover {
  background: #777;
  cursor: pointer;
}
```

**Screenshots**
<img width="786" alt="Screen Shot 2019-12-06 at 10 28 23 AM" src="https://user-images.githubusercontent.com/314122/70326677-dda14380-1813-11ea-89dd-0c905fdc3ff1.png">

**Comment by asmyshlyaev177** [comment]
Does it works without menu?

**Comment by eliasturbay** [comment]
yes @asmyshlyaev177, it was working fine before. I decided to use your library to avoid having to handle all the scrolling and dragging events

**Comment by asmyshlyaev177** [comment]
Can you try to set 'white-space: normal;' to your item?

**Comment by eliasturbay** [comment]
Thank you so much @asmyshlyaev177 ! Works like a charm! 😄
