### ISSUE TITLE
idea new option : detect if all arrows are disabled

### ISSUE THREAD

**Issue by NevaRgtm** [asmyshlyaev177/react-horizontal-scrolling-menu#85]
Hello Alex,

i was using the component; and i'm trying to hide arrows when `arrow-prev` and `arrow-next` are **disabled** (opacity: 0), and show the arrows when i have only one disabled (put in grey the arrow) with different class css.

Maybe, I have missed an option, or it's possible to add an option to distinguish the 2 possibility?

I see 2 solutions with  differents class css on element:

- If the 2 arrows are disabled : an class like "hide" on `arrow-prev` and `arrow-next` or on an parent element.

- or, if only one arrow is disabled : keep `disabled` or a class like `start line`/`end-line`

**Comment by asmyshlyaev177** [comment]
Don't understand what you trying to do.

Have `arrowDisabledClass` prop, by default if arrow disabled(left arrow in start of list) added class `scroll-menu-arrow--disabled` to arrow.
