### ISSUE TITLE
useButtonRole={false} still adds empty role parameter

### ISSUE THREAD

**Issue by grrowley** [asmyshlyaev177/react-horizontal-scrolling-menu#86]
Using the prop `useButtonRole` and setting it to false to remove the implied element role still creates the role attribute on the element. This is creating an error in my accessibility tests.
```
New aXe issues
index.js:182 critical: ARIA roles used must conform to valid values
<div class="menu-item-wrapper " tabindex="0" role="" style="display: inline-block;">...</div>
```
I suggest if `useButtonRole` is false not to add the role attribute at all...Or even better: if `useButtonRole` is a string allow the user the provide the desired role.

**Comment by asmyshlyaev177** [comment]
Fixed in 0.7.5
