### ISSUE TITLE
Lazy loading to pull new data when reach end of the scroll data

### ISSUE THREAD

**Issue by mozartatplay** [asmyshlyaev177/react-horizontal-scrolling-menu#87]
It would be great if I could pull more data from my database when I reach the end of a list (similar to how netflix keeps loading data as you reach the end of the scroll)

Is there a way to detect when the end of the data is reached when clicking the right scroll button or swiping and reaching the end of the data. 

Thanks
David

**Comment by asmyshlyaev177** [comment]
Have internal method - `$r.checkFirstLastItemVisibility({})` it will return object `{firstItemVisible: false, lastItemVisible: false}`.
But it check arrows async, so immediately after you scroll to last element `lastItemVisible` will change after few milliseconds.

Can try to use `isScrollNeeded = ({ itemId: menuItem-24 })`, (for 25 items, 24 will be index of last item)
Have `getVisibleItems({})`, can get visible items.

**Comment by mozartatplay** [comment]
Excellent - thanks for the help I got this working now with the following code. I use settimeout() to create a delay before I check checkFirstLastItemVisibility({})

TitlesClickRightArrow = () => {
    //console.log('Search: Titlesclickleftarrow')
    //console.log('Search: Met condition Titlesclickleftarrow')
    this.menu1.handleArrowClickRight();
    
    var lazyload, newTitleCount, newSearch

    setTimeout(() =>  {
      var newLastVisible = this.menu1.checkFirstLastItemVisibility({})['lastItemVisible']
      lazyload = this.state.lastItemVisible && newLastVisible
      console.log('Browser List onUpdate: ', this.state.lastItemVisible, newLastVisible, lazyload )
      console.log('Browser List: Lazyload', lazyload)
      if (lazyload) {
      
        console.log('Browser List: titleCount: ', this.state.titleCount)
        if (this.state.titleCount < MAXTITLES)  {
          newTitleCount = this.state.titleCount + 10;
          this.setState({loading:true, titleCount: newTitleCount, lastItemVisible: newLastVisible, pendingRightShift: true});
          newSearch = false;
          this.SearchTitle(this.state.searchYear,this.state.searchRating,this.props.title,newTitleCount,true,newSearch)
        }
        else 
          this.setState({reachedLastTitle: true})
      }
      this.setState({lastItemVisible: newLastVisible})
    }, 500 ) 
    
   
  }

**Comment by mozartatplay** [comment]
Its looking really great now - here is a video capture
https://www.dropbox.com/s/eysg8eg7vw455tj/scrolling_myapp.mov?dl=0

Thanks you Alex for a truly fantastic piece of software!

**Comment by asmyshlyaev177** [comment]
Thank you, glad this package useful.

I think you can run `setTimout` with 0 interval. Ideally without setTimeout at all, it cause some glitch before items fetched.

Better start fetch next items not when last item visible, but one click before it.
Something like 
```
// if have 30 items, check that 23-rd item (30-7) visible
const last_item_will_be_visible_soon = isScrollNeeded({ itemId: `menuItem-${all_items.length - 7}` })
if (last_item_will_be_visible_soon) { 
... fetch_new_items ...
 }
```

**Comment by asmyshlyaev177** [comment]
Btw added `onFirstItemVisible` and `onLastItemVisible` callbacks, and updated example app.
