### ISSUE TITLE
When wrapping component with container element that has fixed position

### ISSUE THREAD

**Issue by dobrea-v** [asmyshlyaev177/react-horizontal-scrolling-menu#88]
**Describe the bug**
When you try to wrap components in a styled element which has position:fixed; suddenly on drag event, menu scrolls back to initial position. 

**To Reproduce**
1. Setup basic component, from docs.
2. Wrap component in a div with position:fixed;
3. Try to scroll.

Please correct, if i am doing smth wrong.

P.S: Thanks for this nice lib

**Comment by dobrea-v** [comment]
Okay,  sorry for this one, i should've added menuStyle={{width: '100%'}}

**Comment by asmyshlyaev177** [comment]
Hi, items not supposed to have position **fixed** , menu items should not be *fixed* in one position.
Normally elements should have position **relative** or **static**

> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none 

[https://developer.mozilla.org/en-US/docs/Web/CSS/position](url)

**Comment by dobrea-v** [comment]
I think you got me wrong, i wanted to wrap ScrollMenu in a div that has position: fixed; not it's items. As i said i figured this out, i had to add menuStyle prop width of 100%.

Thanks for response
