### ISSUE TITLE
Add new function

### ISSUE THREAD

**Issue by thedarkzeno** [asmyshlyaev177/react-horizontal-scrolling-menu#89]
Is it possible to add a new function?
I would like to have something like onEndReached, so I could execute a function that loads new content once you scroll to the final item.
thanks =)

**Comment by asmyshlyaev177** [comment]
Will think about it.

**Comment by asmyshlyaev177** [comment]
Added `onFirstItemVisible` and `onLastItemVisible` callbacks, and updated example app.
