### ISSUE TITLE
Empty space appearing on resize

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#9]
Hello
![scroll](https://user-images.githubusercontent.com/1753208/46281707-1ee6f500-c578-11e8-9584-37098558da24.gif)

Other than that - great plugin, well done!

**Comment by asmyshlyaev177** [comment]
Will do something for align items after resize.

Thanks! I am glad if somebody use plugin.

**Comment by asmyshlyaev177** [comment]
Fixed in [0.3.0](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/releases/tag/0.3.0)

**Comment by NeXTs** [comment]
Awesome!
