### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by aZolo77** [asmyshlyaev177/react-horizontal-scrolling-menu#90]
I'm trying to make dropdown menu VS scrolling menu, but it is not possible, cause .slide-menu__wrapper has "overflow: hidden"
Can i do something to make all this work together?

**Comment by asmyshlyaev177** [comment]
Can pass `wrapperStyle` prop with your own styles.

**Comment by aZolo77** [comment]
> Can pass `wrapperStyle` prop with your own styles.

Sure! But if i make "overflow: visible;" horizontal scroll appears on the whole page

**Comment by asmyshlyaev177** [comment]
Can pass `overflow: auto;` or `overflow: inherit;`.
I guess horizontal scroll will appears without this component too.

**Comment by aZolo77** [comment]
> Can pass `overflow: auto;` or `overflow: inherit;`.
> I guess horizontal scroll will appears without this component too.

I found main problem - its translate3d property, that prevents dropdown menu to be visible..
And I found one decision - to replace translate3d on simple margin-left property, but i cant handle it, cause its value is calculating somewhere inside yr library funcs - can you help with this, please?

**Comment by asmyshlyaev177** [comment]
I'm afraid can't do anything with `translate` it how all items scroll. It also give better performance than margin.

Can you reproduce it on codesandbox?

**Comment by aZolo77** [comment]
Its ok! I found another decision - create submenu copy and prepend them to parent element and then delete...
