### ISSUE TITLE
Problems with scroll menu disabled class in left arrow

### ISSUE THREAD

**Issue by gstvribs** [asmyshlyaev177/react-horizontal-scrolling-menu#92]
When HideArrows is enabled, scroll-menu-arrow--disabled is applied all the time to the left arrow, i personally believe that this behavior should only happen if the elements do not fit the screen.

Sometimes you just want to remove all arrows when elements fit in the screen, but when the items did not fit, the left arrow continues to appear

I could work on this PR

**Comment by asmyshlyaev177** [comment]
Can you reproduce it?

**Comment by gstvribs** [comment]
I have a list with ten items, and the items did not fit in the screen (but the left arrow, apply the disabled class)
![image](https://user-images.githubusercontent.com/7907966/75636027-e2e71200-5bf9-11ea-9aba-c02cfccebed8.png)

Now, items fits on the screen. (and the disabled class is applied to both arrows
![image](https://user-images.githubusercontent.com/7907966/75636054-26418080-5bfa-11ea-8f42-37b92819231b.png)

**Comment by asmyshlyaev177** [comment]
Left arrow disabled if first item visible(so if can't scroll left).

In second case can't scroll neither left or right, so both arrows disabled.

**Comment by gstvribs** [comment]
The problem is because the item called "Maria" is visible and it's applying the disabled class

**Comment by gstvribs** [comment]
I thinks this behavior only could happen if hideSingleArrow is enabled
