### ISSUE TITLE
On first load, translate seems to be ignored.

### ISSUE THREAD

**Issue by harel** [asmyshlyaev177/react-horizontal-scrolling-menu#93]
I'm not sure if this is a bug or a misconfiguration. 
Menu is within in iframe. 
I'm explicitly stating `translate={0}` in my properties. However, the first time the panel loads the first item in the scroll menu is right of the left arrow. After scrolling it then resolves to the left, going underneath the arrow (which is what I want). 
What makes it strange is subsequent reloading of the frame this is in, the frist item is ok - under the arrow. It's only the first time the entire page is loaded. 

How can I force the menu inner wrapper to always start at about 0-5 pixels from left?

Chrome 79, Linux/Ubuntu 

![Screenshot from 2020-03-01 15-19-18](https://user-images.githubusercontent.com/985978/75628412-95a27a80-5bd0-11ea-9046-25122ee19ce1.png)

Initial load. Menu starts just after the arrow (transform is shifted to 45.1px). 

![Screenshot from 2020-03-01 15-18-29](https://user-images.githubusercontent.com/985978/75628434-db5f4300-5bd0-11ea-9012-9e5165c9c071.png)

After first scroll, or subsequent reloads of just the frame itself.

**Comment by asmyshlyaev177** [comment]
Can try to set `alignCenter={false}`

**Comment by harel** [comment]
Yes that worked!! Thanks
