### ISSUE TITLE
Menu shows two rows in development mode but one in production?

### ISSUE THREAD

**Issue by rohail411** [asmyshlyaev177/react-horizontal-scrolling-menu#94]
I am creating a web application using React.js using react-horizontal-scroll-menu for showing 2-row cards it works fine in development but not in production. here you can see the images.
**In Development:**
![true](https://user-images.githubusercontent.com/47238303/75667913-445ebd80-5c9a-11ea-9c01-f2f5c157da62.PNG)
**In Production:**
![errorrrrr](https://user-images.githubusercontent.com/47238303/75667947-54769d00-5c9a-11ea-8e9f-efd51b54e4af.PNG)

**Comment by asmyshlyaev177** [comment]
Can you reproduce it somehow?

**Comment by rohail411** [comment]
I don't understand what you can say?

**Comment by asmyshlyaev177** [comment]
Will try to reproduce it when have time.

**Comment by gstvribs** [comment]
Any configurations changes in development or production?

**Comment by rohail411** [comment]
no same in both cases

**Comment by gstvribs** [comment]
There's no reason to lib do that, as in see the lib do not have any difference by development and production

Do you confirm, that you data list, still the same on both environments?
