### ISSUE TITLE
Disable swiping while the parent width is enough for all items

### ISSUE THREAD

**Issue by vodanh109** [asmyshlyaev177/react-horizontal-scrolling-menu#95]
Hi, can the library disable swiping while the parent width is enough for all items?

**Comment by asmyshlyaev177** [comment]
Hi, it can't for now.
Can disable drag completely like `dragging={false}`.

**Comment by sachinkotwal** [comment]
Is there any plan to add this enhancement?

**Comment by asmyshlyaev177** [comment]
Not so much time for project recently, plan to rewrite it completely in better way.

If you assign ref to `ScrollMenu` component you can check this condition `menuRef.getWidth()` it will give you `menuWidth` and `allItemsWidth`
so can store these values and pass like `dragging={allItemsWidth && menuWidth && allItemsWidth > menuWidth}`

**Comment by asmyshlyaev177** [comment]
Can you check V2?
