### ISSUE TITLE
scroll-menu-arrow--disabled not set on inital page load

### ISSUE THREAD

**Issue by dsimonds-metagenics** [asmyshlyaev177/react-horizontal-scrolling-menu#97]
**Describe the bug**
When a page first loads the left arrow does not set scroll-menu-arrow--disabled, only after page reload or window resize is the class set.

**To Reproduce**
Create scroll menu and load page, left arrow will appear and class will not be set.

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by asmyshlyaev177** [comment]
It disabled in demo app. Checked it right now it works.
![Screen Shot 2563-03-10 at 18 49 22](https://user-images.githubusercontent.com/19854148/76309727-ebc59b00-62ff-11ea-9aaa-ae054564a34c.png)

Please reproduce it on codesandbox.

**Comment by dsimonds-metagenics** [comment]
Please find sandbox below

https://iid2u.csb.app/

**Comment by dsimonds-metagenics** [comment]
Initial page load is the wrong description, sorry. I should have put when routing from another page it does not set the class.

**Comment by asmyshlyaev177** [comment]
I mean i need example that reproduce bug.

**Comment by asmyshlyaev177** [comment]
Can you at least assign some ref to menu and call `menuRef.setFirstLastItemVisibility()`
And look, is class applied or not.

**Comment by dsimonds-metagenics** [comment]
CodeSandbox error doesn't show on route change, must reload the iframe on each page. Please find a screenshot with it not working.
![image](https://user-images.githubusercontent.com/60086963/76489893-695ee780-6475-11ea-98d9-d503b2b43966.png)

**Comment by dsimonds-metagenics** [comment]
Do you need any other information to see what may cause the issue? @asmyshlyaev177

**Comment by asmyshlyaev177** [comment]
Please try out V2, it should works fine there, won't support V1 anymore.
