### ISSUE TITLE
Select multiple items and select and un select particular item

### ISSUE THREAD

**Issue by saikumar0596** [asmyshlyaev177/react-horizontal-scrolling-menu#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by asmyshlyaev177** [comment]
Will think about it, currently is not supported.

**Comment by narayansiddhu** [comment]
![Screenshot 2020-03-16 at 12 16 38 AM](https://user-images.githubusercontent.com/16466429/76708253-743aa600-671b-11ea-9cd9-66587bc57be0.png)

**Comment by narayansiddhu** [comment]
trying to implement multiple selections. but not working.

**Comment by pengw00** [comment]
> trying to implement multiple selections. but not working.

what's is your solution?

**Comment by Markusdreyer** [comment]
Would be great to have deselect functionality!

**Comment by pengw00** [comment]
you can change the onSelect function to implement multiselectable though

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0` there can do this.
